### ISSUE TITLE
Typos in English text (documentation, comments, ...)

### ISSUE THREAD

**Issue by stweil** [rdmorganiser/rdmo#1001]
### Description / Beschreibung

The current code contains English typos which can be found and fixed using tools like `codespell` or `typos`.

### Expected behaviour / Erwartetes Verhalten

Minimizing the number of typos helps users and developers, so known typos should get fixed.

### Steps to reproduce / Schritte zum Reproduzieren

1. Run a spell checker (see suggested ones above).

### Context / Kontext

Not relevant

**Comment by jochenklar** [comment]
Will be releases in RDMO 2.2.
