### ISSUE TITLE
Add `typos` to pre-commit config

### ISSUE THREAD

**Issue by afuetterer** [rdmorganiser/rdmo#1005]
Ref: https://github.com/crate-ci/typos

**Comment by jochenklar** [comment]
Yes, thanks for the idea. `typos` is easily installable using `pip`. But we need to exclude the `_de`/`_fr` files.

**Comment by afuetterer** [comment]
Yes, a few files/directories should be excluded. Will submit a PR soon.

**Comment by jochenklar** [comment]
Awesome, thanks!
