### ISSUE TITLE
Make real links visible

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo#1007]
![grafik](https://github.com/rdmorganiser/rdmo/assets/37865804/3299914d-a999-4183-ad09-4465b2b71f19)

The preview of this link shows the present page https://rdmocat.aip.de/management/catalogs/20/nested/. When copying the link, we get the same one.

Instead, by clicking on it, we get the real target link https://rdmocat.aip.de/management/questions/170/ .

The target link should appear in all positions.

**Comment by jochenklar** [comment]
Will be part of RDMO 2.2.0.
