### ISSUE TITLE
Buttons "Create new question" and "create new questionset" swapped

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo#1009]
### Description / Beschreibung

The button "Create new question set" allows creating single questions and the button "Create new questions" allows creating questionsets.

![grafik](https://github.com/rdmorganiser/rdmo/assets/37865804/81a9bf60-2c52-4932-9432-ab7183ec7f2d)

**Comment by jochenklar** [comment]
Thanks @Zack-83, but this is already fixed (but not released). https://github.com/rdmorganiser/rdmo/issues/944 Maybe I should close issues only after the release... but then the progressbar of the milestone would not work.

**Comment by Zack-83** [comment]
> Thanks @Zack-83, but this is already fixed (but not released). #944 Maybe I should close issues only after the release... but then the progressbar of the milestone would not work.

Thanks Jochen, of course it's fine to close issues! Now I know that how to cope with the problem until the instance administrators have a valid reason to update
