### ISSUE TITLE
Collections in Views

### ISSUE THREAD

**Issue by skelligan** [rdmorganiser/rdmo#105]
If I understand the documentation at https://rdmo.readthedocs.io/de/latest/management/views.html correctly, the following statements should produce the same output, one with an inline-list, the other one with a multi-line list:
1) `{% render_value_inline_list 'project/general/basics/management' %}`
2)
```
<ul>
{% for i in 'project/general/basics/management' %}
    <li>{% render_value i %}</li>
{% endfor %}
</ul>
```

However, while the first statement producing an inline-list works fine, the second statement only produces loads of bullets with no text at all.
Am I doing something wrong or does this not work as intended?

PS. The documentation is not consistent between the German and English version where the attributes and their values are explained.

**Comment by skelligan** [comment]
Great, thank you for the help.

**Comment by triole** [comment]
Closing as it seems to be settled.
