### ISSUE TITLE
projects overview edge-case: it stays empty when a filtered catalog was deleted (error in fetch)

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#1077]
### Description / Beschreibung

projects overview edge-case: it stays empty when a filtered catalog was deleted (error in fetch). 
Filter can't be restored by refresh because of local storage..

### Expected behaviour / Erwartetes Verhalten

reset the filter when fetch fails

### Steps to reproduce / Schritte zum Reproduzieren

1. Go to Projects overview
2. Click on filter for catalog
3. Delete the catalog
4. Go to Projects overview and See error (empty page)

### Context / Kontext

Browser

### References / Verweise

*

**Comment by CalamityC** [comment]
Will be released in 2.2.0

**Comment by CalamityC** [comment]
Will be released in 2.2.0
