### ISSUE TITLE
Bug in interview in the (dis)appearance of a conditional question in combination with a checkbox question and datasets

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#1103]
### Description / Beschreibung

A certain question (is_collection, Checkboxes and Option) with checkboxes should show another conditional question when one of the checkboxes is selected.

New project (front end):
When starting a new Project and creating a first dataset, the conditional question appears (without having selected any checkbox). Upon selecting one (other) checkbox the conditional question disappears and progress appears. After this the conditional question and progress follow the normal behaviour when the special checkbox is selected.

Existing project (back end):
In another existing project, the condition does not resolve correctly anymore (possibly due to wrong `set_index`?).
The progress seems to show the total of all possible questions even when only one of the datasets has selected for this conditional question. (seems to show as if all datasets would have this conditional question)

### Expected behaviour / Erwartetes Verhalten

Initially, don't appear. Progress total follows the questions/answers of the datasets.

### Steps to reproduce / Schritte zum Reproduzieren

bit complicated to set up, see description

### Context / Kontext

2.1.3

### References / Verweise

* maybe somehow related to fix in https://github.com/rdmorganiser/rdmo/pull/1058
* Refactor progress bar and take sets and conditions into account (https://github.com/rdmorganiser/rdmo/issues/596) 
  * https://github.com/rdmorganiser/rdmo/commit/41c92fae147c14e863b24e8ee05a0c8930ae6217#diff-25b1369af96351f580e8fb459e5883f555b3d43b97119d662df058b14833a872
* reproduced locally with mini catalog (can't share the .xml file here)
* https://github.com/rdmorganiser/rdmo/blob/065d195043b7ac34a7b6b3180dac69829a3974bc/rdmo/projects/progress.py#L85

**Comment by jochenklar** [comment]
This was fixed, right?

**Comment by MyPyDavid** [comment]
yes, 2 PRs with 2 fixes!
