### ISSUE TITLE
Use `npm ci` in CI

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#1115]
I am not sure, but I think we should use `npm ci` here: https://github.com/rdmorganiser/rdmo/blob/main/.github/workflows/ci.yml#L160 to catch if our lock file diverged from `package.json`.

**Comment by afuetterer** [comment]
I wanted to point this out as well. I was unfamiliar with that, when I added the ci job.

Please go for it.

**Comment by MyPyDavid** [comment]
there is a PR with a minimal change for this

**Comment by MyPyDavid** [comment]
merged in 2.2.0 release
