### ISSUE TITLE
build: pin the dependencies to ranges with minimum and maximum versions for each package

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#1119]
### Rationale / Begründung

As already discussed, the current dependency notations with `~=` do not yield well-defined environments, which can lead to version/dependency conflicts. 
The pinning to min and max version ranges would prevent this and allows the proper dependency versions to be installed with
 `pip install rdmo` or `pip install -e .` etc..

### Affected

Who is affected by the change (Users, Managers, Admins)?

### Minimal functionality

* minimum `>=` and maximum `<`

### References / Verweise

*

**Comment by afuetterer** [comment]
Does this really change anything?

According to
https://peps.python.org/pep-0440/#examples
I think
`~=3.1: version 3.1 or later, but not version 4.0 or later.`
and
`>=3.1 <4.0` are equivalent?

**Comment by MyPyDavid** [comment]
from that pep it might look equivalent 😅  but I think that we just remove the `~` notation now to prevent confusion about this

**Comment by jochenklar** [comment]
I just tested it and it is like you (and the PEP) says. Sorry for the confusion. I was pretty sure it was different, but I must have messed something up back then. But as @MyPyDavid says: lets move to the more explicit notation.

**Comment by MyPyDavid** [comment]
merged in 2.2.0 release
