### ISSUE TITLE
No questionaire displayed

### ISSUE THREAD

**Issue by olf42** [rdmorganiser/rdmo#114]
I ran into a strange error, after setting up the latest version of rdmo:
> rdmo==0.12.0

I successfully imported the contents of the `rdmo-catalog` repository and created a test project, then when I try to answer the questions (e.g. of the RDMO catalog) for a split second "Thank you for answering the questionaire" is displayed, before the page is blanked. 

![2019-02-20-070835_3000x1920_scrot](https://user-images.githubusercontent.com/7475681/53070202-a0ff9800-34de-11e9-8287-81b9aed7b870.png)

I suspect it being a javascript issue, as the console reads:

> Error: question.attribute is null
> service.fetchValues/<@http://XXX/static/projects/js/project_questions/services.js:301:21
> q@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8//angular.min.js:7:353
> service.fetchValues@http://XXX/static/projects/js/project_questions/services.js:300:13
> service.initView/<@http://XXX/static/projects/js/project_questions/services.js:99:24
> e/<@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8//angular.min.js:131:20
> $eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8//angular.min.js:145:343
> $digest@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8//angular.min.js:142:412
> $apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8//angular.min.js:146:111
> l@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8//angular.min.js:97:320
> J@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8//angular.min.js:102:34
> gg/</t.onload@https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8//angular.min.js:103:4
>  angular.js:13920:17
> e9Angular

I deployed the application using docker-compose with postgres 11.2 as database.

**Comment by triole** [comment]
The mentioned error message does look familiar which luckily gives me an idea what could have gone wrong. Important is the first line of your posted error message: `Error: question.attribute is null`. An attribute of the domain model seems to be mising. Namely one of the questions that RDMO is trying to load when you open the page where the problem occurs. Please make sure that you fully imported the RDMO domain model. If you did please check if the question that you are expecting to load does have an attribute in your domain model tree.
