### ISSUE TITLE
Update 2.1.3 to 2.2.0 failed with Shibboleth enabled and allauth disabled

### ISSUE THREAD

**Issue by kzimmermann836** [rdmorganiser/rdmo#1145]
### Description / Beschreibung

I cannot update our RDMO instance from version 2.1.3 to 2.2.0. The step "python manage.py migrate" displays an error message.

### Steps to reproduce / Schritte zum Reproduzieren

1. source env/bin/activate
2. pip install --upgrade rdmo
3. python manage.py migrate
4. See error:
RuntimeError: Model class allauth.account.models.EmailAddress doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

### Context / Kontext
Operation system: Debian 11
RDMO version: 2.1.3

We use Shibboleth for authentication. 
Authentication with allauth is not enabled.
The previous update from 2.1.2 to 2.1.3 in February 2024 ran without problems.

**Comment by jochenklar** [comment]
Hi @kzimmermann836 , thanks for reporting. I already found the bug and we will publish a Version `2.2.1` later this week.

**Comment by kzimmermann836** [comment]
Hi @jochenklar, thanks for the bugfix. Today I updated from 2.1.3 to 2.2.1 successfully, it worked without any problems.
