### ISSUE TITLE
Missing Section/Page Titles and Question Texts

### ISSUE THREAD

**Issue by MarcoReidelbach** [rdmorganiser/rdmo#1148]
### Description / Beschreibung

Following the update from v2.1.3 to v2.2.1 the Section/Page Titles and Question Texts seem to be missing, when going through the interview (in the actual interview and in the navigation). Only help texts and text fields (etc) for the answers are displayed. Pages that require a condition to be fullfilled are displayed in the navigation, but vanish from the navigation once the condition is fullfilled.      

### Expected behaviour / Erwartetes Verhalten

Question Texts in the interview and Section/Page Titles in the navigation.

### Steps to reproduce / Schritte zum Reproduzieren

1. Go to some project
2. Click on 'Answer Questions'
3. See Missing Texts

![Screenshot from 2024-09-16 10-15-25](https://github.com/user-attachments/assets/db8fd23d-3a6a-4588-aefa-82c5acc54e7e)

### Context / Kontext

RDMO v2.2.1 tested locally on Ubuntu 22.04

**Comment by jochenklar** [comment]
Hi @MarcoReidelbach , this could be a problem with locally cached js files, can you check?

**Comment by MarcoReidelbach** [comment]
I (believe I...) cleared the cache and also installed RDMO v2.2.1 from scratch with the same outcome.
