### ISSUE TITLE
Changes done while form data is saved are overwritten 

### ISSUE THREAD

**Issue by cfgmr** [rdmorganiser/rdmo#115]
When I change something in a form and hit save, all subsequent changes in the same form are overwritten once saving (as indicated by gray circle on top right) is done, i.e. the data that was saved is re-loaded, overwriting any intermediate changes.

This is an issue since in our RDMO installation, save times can be 5-10 seconds on custom forms. This means if you noticed a typo after hitting save, you need to wait. Also took me a time to become aware of this issue, resulting in some glitches in my workflow...

I would suggest to either not re-load the saved data or to prevent intermediated changes, e.g. by disabling inputs.

cc @Maaike74

**Comment by jochenklar** [comment]
Hi, when you save a questionset all fields are communicated to the server. This might be a problem for a large number of questions and/or sets. For us it was never a problem, but if your use case is different we might to change that in the future.

Can you tell us how many sets (or tabs) and how many questions are in you questionset?

**Comment by cfgmr** [comment]
Hi, thanks for the answer.
> Can you tell us how many sets (or tabs) and how many questions are in you questionset?

There are currently 27 tabs and 9 questions per tab. Saving takes well over 10 seconds.

**Comment by jochenklar** [comment]
Ok, finally a power user :smiley:!

We need to find a solution for that.

**Comment by jochenklar** [comment]
From RDMO 1.6 on only answers which where changed are saved to the server, this should solve this issue.
