### ISSUE TITLE
Save and proceed will select wrong tab

### ISSUE THREAD

**Issue by cfgmr** [rdmorganiser/rdmo#116]
When adding/ editing a 'New Data Collection', after filling the basic data form, I hit 'Save and proceed' to edit the 'New Data Collection - Details' page. I expect to be taken to the tab with the details of the data collection I just came from. This is not the case. Instead, the first tab of the 'New Data Collection - Details' page is selected, no matter from which page I come from.

This is especially annoying since the tabs for custom forms do not show the name given to the item but rather '#1, #2, #3, ...' making it difficult to select the right tab to edit the details in.

cc @Maaike74

**Comment by jochenklar** [comment]
Hi, thanks for the feedback! Right now, the 'Save and proceed' button proceeds to the next page, or, when multiple sets exist, to the next set. Your expectation is different and we now need to figure out how the flow of input can be improved (for most users). Maybe we will add another button, but this needs some more thought (and time), I'm afraid.

**Comment by cfgmr** [comment]
Hi Jochen,

when I submitted the issue, I found 'Save and proceed' did not select the next set but always the *first* set. We had an update since then and now it works as you described. It might also be that I was always on the last tab when testing, in which case the next tab would be the first...

Anyway, it now works as it should and I can see why it works how it works.
👍
