### ISSUE TITLE
Unwanted markdown conversion in Section title

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#1184]
### Description / Beschreibung

We have a user that set a numbering on the section titles of a catalogue, eg. "1. Title".
This is now with markdown converted in to a `<ol>` list element and appears strangely in the interview.

Section and other element titles don't need a list element in their markdown conversion I would guess.
Should we specify and strip certain html elements depending on which rdmo element field does the conversion?
Otherwise, can we add an ignore string to the conversion method?
Any other suggestions?

### Expected behaviour / Erwartetes Verhalten

Have a section title with text  "1. Title" be displayed normally .

### Steps to reproduce / Schritte zum Reproduzieren

1. add a section title with text  "1. Title" 
2. go to interview and see markdown converted `<ol>` in the section title

### Context / Kontext

Version 2.2.1

### References / Verweise

* `rdmo/projects/templates/projects/project_questions_head.html`
* `rdmo/projects/templates/projects/project_questions_navigation.html`
* https://github.com/rdmorganiser/rdmo/blob/1eadee51947399601d85e476b261391826e0f95a/rdmo/core/utils.py#L371

* https://daringfireball.net/projects/markdown/syntax#list
```
Ordered lists use numbers followed by periods:

1.  Bird
2.  McHale
3.  Parish

It’s important to note that the actual numbers you use to mark the list have no effect on the HTML output Markdown produces. 
The HTML Markdown produces from the above list is:

<ol>
<li>Bird</li>
<li>McHale</li>
<li>Parish</li>
</ol>

````

**Comment by jochenklar** [comment]
Hmm, it makes no sense to have `ol` (or `ul`) in the titles or the text of a question, but in a help text it makes sense. I am a bit hesitant to create different markdown workarounds for different fields and different markdown features. The easiest solution would be to escape the syntax: `1\. Title`.
