### ISSUE TITLE
npm build warnings in CI

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#1197]
I think it would be good if this warning would stop the CI:

```
  WARNING in ./rdmo/projects/assets/js/projects/components/helper/PendingInvitations.js 25:41-48
  export 'default' (imported as 'baseUrl') was not found in 'rdmo/core/assets/js/utils/meta' (possible exports: baseUrl, language, siteId, staticUrl
```

Any ideas @MyPyDavid @afuetterer ?

**Comment by MyPyDavid** [comment]
Ive added some settings to the webpack.config in here https://github.com/rdmorganiser/rdmo/pull/1203, it should fail at the `build:prop` because of that warning.

**Comment by MyPyDavid** [comment]
we have now `build:dist` that fails on non-performance warnings.
