### ISSUE TITLE
rdmo exports xml elemts multiple

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#126]
When exporting a rdmo domain via xml export individual database entries are being written multiple of what was a single database entry. 

I expect this issues to be resolved, when the xml export has only a single xml element per database entry. 

: RDMO v0.12
: python3 
: local install sqlite3

**Comment by Bassbiest** [comment]
A strong hint might be, that each descendant of the main attribute 'project' is exported the exact amount of times that corresponds to its position in the descendency , i.e. the main attribute is exported once, children of the main attribute are exported twice, children of the first children are exported thrice and so on.

**Comment by jochenklar** [comment]
Thanks for reporting, we will look into it soon.

**Comment by jochenklar** [comment]
Fixed in 01346bab82b34c945e2ea9704cdd7f90db4849d7.
