### ISSUE TITLE
Sort / Filter / Visualize questions according to catalogue in admin mode

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo#132]
When in admin mode (e.g. https://rdmo.aip.de/admin/questions/question/), it would be comfortable to see / group only the questions belonging to one specific catalog. It should be easy to add one filter "facet" on the right.

**Comment by jochenklar** [comment]
Yes, indeed, we will add that soon.

**Comment by jochenklar** [comment]
Added in 4f47fdcda682d1826cbe1b38b8de828680add42b.
