### ISSUE TITLE
403 Error when trying to delete project as author

### ISSUE THREAD

**Issue by Bassbiest** [rdmorganiser/rdmo#138]
I was added to a project as an author and when I try to delete the project I am redirected to a 403 error page. 

Tested with v0.14.4

Add an internal error message telling the user he can't delete the project because he is not the owner.

**Comment by jochenklar** [comment]
Yes, this is not implemented, only managers and owners can remove people from projects (hence 403). We will fix it soon™.

**Comment by triole** [comment]
Fixed. You can remove yourself from a project even if you are only author.
