### ISSUE TITLE
Incompatible `djangorestframework` dependency

### ISSUE THREAD

**Issue by JKatzwinkel** [rdmorganiser/rdmo#145]
As of release of `djangorestframework==3.10.0`, the decorator `@list_route` is no longer available (see eg. sunscrapers/djoser#404). This means that `rdmo` installed from the cheese shop won't run (i.e. affecting the docker-compose setup). You could probably fix this temporarily by freezing the `djangorestframework` dependency on `==3.9.4`.

**Comment by jochenklar** [comment]
Thanks for reporting. I allready fixed it in 3e92a28b992418fa991f9c3d54c919e43bd2bc52. A new version on PyPI will follow this week.

**Comment by jochenklar** [comment]
New version is out: https://github.com/rdmorganiser/rdmo/releases/tag/0.14.5

**Comment by JKatzwinkel** [comment]
nice thanks!!
