### ISSUE TITLE
Can not add Attribute (400 Bad Request)

### ISSUE THREAD

**Issue by FabianHamm** [rdmorganiser/rdmo#149]
I just installed RDMO 0.14.5 and imported the rdmo catalog (rdmorganiser). When trying to add a new attribute "reuse_existing" to attribute "project/dataset/" nothing happens after clicking on save.

I found this in the browser log:

POST http://xxx.xxx.xxx.:14226/api/v1/domain/attributes/ 400 (Bad Request)
(anonymous) @ angular.js:12011
n @ angular.js:11776
(anonymous) @ angular.js:11571
(anonymous) @ angular.js:16383
$eval @ angular.js:17682
$digest @ angular.js:17495
$apply @ angular.js:17790
(anonymous) @ angular.js:25890
dispatch @ jquery-3.2.1.min.js:3
q.handle @ jquery-3.2.1.min.js:3

--- Request Payload ---
{"parent":39,"uri_prefix":"https://rdmo.uni-xxx.de/terms/","key":"reuse_existing"}

--- Response ---

{"path":["Dieses Feld wird ben\u00f6tigt."]}

**Comment by FabianHamm** [comment]
Just tried it via the API. Sending the payload with set path property through curl works (i.e. 201 Return code) ...

**Comment by jochenklar** [comment]
Hi, thanks for reporting. The was something very wrong in the serializer for Attributes. It should be fixed in 1e7d61436657d06814f733c36dd45946df6edff6.

**Comment by FabianHamm** [comment]
Thank you for fixing, it works now. I'm closing the issue.
