### ISSUE TITLE
URL assembly in mails

### ISSUE THREAD

**Issue by m6121** [rdmorganiser/rdmo#150]
E-mails (and possibly other parts of rdmo) contain a URL, e.g. for the confirmation of the mail address: http://<site>/account/confirm-email/<key>/
In our case the URL does not reflect the HTTPS encryption which we use for the site and instead uses the HTTP protocol. How can this behaviour be changed so that HTTPS encryption is enforced?

Installation via rdmo-docker-compose set up and nginx using as a proxy server.

**Comment by jochenklar** [comment]
Hi, if you use a reverse proxy you need to set the HTTP header 'X-Forwarded-Proto' to 'https', e.g. for nginx:

```
proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by m6121** [comment]
Setting this in Nginx which serves as reverse proxy to the docker set up does unfortunately not resolve the problem. May it the problem result from the apache config within the docker-compose setup which uses http only?

**Comment by jochenklar** [comment]
Yes, the apache in the docker container needs to set this header as well. I will have a look.

**Comment by jochenklar** [comment]
I forgot something which we didn't document properly. You need to set:

```
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
```

in your `config/settings/local.py` in order for django to pick up the headers set by the proxy. I will fix that in the documentation.

**Comment by m6121** [comment]
Adding these configuration options resolves the problem. Thanks a lot for your investigation!
