### ISSUE TITLE
Disable Registration/PW reset and change when using LDAP

### ISSUE THREAD

**Issue by m6121** [rdmorganiser/rdmo#151]
When using centralized LDAP authentication. Password and user information should be maintained by the central LDAP server only. A configuration option for disabling Password reset and change for an instance as well as new user registration would be a major enhancement.

**Comment by jochenklar** [comment]
Hi, this can already be done by setting `PROFILE_UPDATE = False` and `PROFILE_DELETE = False` in `config/settings/local.py`. See also: https://rdmo.readthedocs.io/en/latest/configuration/authentication/ldap.html

**Comment by jochenklar** [comment]
And `ACCOUNT = False` and `ACCOUNT_SIGNUP = False`, which should be the default.

**Comment by m6121** [comment]
Thanks a lot! The ACCOUNT and ACCOUNT_SIGNUP settings were set True. Setting them to False resolved this issue even though PROFILE_UPDATE and PROFILE_DELETE have been False before.
