### ISSUE TITLE
[enhancement] Data upload to a project (supplementary data)

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#156]
### Descriptive summary

Supplementary data can be attached to a project.

### Affects

Users and Managers 

### Rationale

RDMO does not allow to display graphic needed for project management, e.g. time line graph, overview table 

### Expected behavior

1. Graphics and table files can be uploaded and attached to a project in RDMO

1. the graphics/table is displayed in `view answers`/export 

### Related work

**Comment by jochenklar** [comment]
This was implemented for RDMO 1.5.
