### ISSUE TITLE
[enhancement] Add draft mode to catalog creation / editing workflow

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#157]
### Descriptive summary

Catalog creation should be carried in draft mode which is only accessible by the manager role and hidden to the normal rdmo user. 

### Affects

Users, Managers and Admins

### Rationale

In case of catalog creation/editing work a second/multiple instances of RDMO are required in addition to a productive one.  

### Expected behavior

Managers have the option to mark catalogs draft/published which hides/shows them from/to the user view.

More atomically draft/published mode is available on the question/question set level. 

### Related work

[issue 46](https://github.com/rdmorganiser/rdmo/issues/46)

**Comment by jochenklar** [comment]
The available flag was added in e9e95ab10f45daae99879e3af8064ed04183a173. Non `available` Catalogs, Views or Tasks can only used who have permissions to access the management interface.
