### ISSUE TITLE
CSS/Font Theming works only with DEBUG = True

### ISSUE THREAD

**Issue by mstuehrenberg** [rdmorganiser/rdmo#163]
Hello,
in our RDMO installation, we've used `python manage.py make_theme` to create the local theme folders.
After that, we've made changes to the `base_footer.html`, the `home_text_de.html`, `home_text_en.html` and the `variables.scss`. All changes worked so far.

As additional theming, we've created copies of the `rdmo/core/static/core/css/fonts.scss` and changed the `@font-face` and `font-family` properties to the font present in our corporate design.

Everything worked fine until we've changed the `DEBUG` parameter in our `local.py` configuration file from `True` to `False` (we've tried commenting out the `DEBUG` line as well with the same effect).

It seems that changes to the fonts.scss (and base.scss) are only considered/evaluated in debug mode -- is this behaviour expected?

**Comment by jochenklar** [comment]
Hi, this is intended. If you run `./manage.py runserver` with `DEBUG=False` you should serve any js or css files. You can force serving static files with `./manage.py runserver --insecure`. See also https://docs.djangoproject.com/en/2.2/ref/contrib/staticfiles/#runserver.
