### ISSUE TITLE
Delete session cookie after shibboleth logout

### ISSUE THREAD

**Issue by amadeusgwin** [rdmorganiser/rdmo#171]
Having logged out after e.g. a successful shibboleth authentification, the set cookie has to be deleted manually. Otherwise the application refers to the shibboleth login page and thus the main RDMO site cannot be visited.

**Comment by jochenklar** [comment]
Hi and sorry for the delay. Shibboleth is complicated business and especially the logout. We will see what we can do.

**Comment by jochenklar** [comment]
This is was fixed in 669cdbd353b9d82a4a4eb4ddf36b15f2107c2c7d and is part of RDMO 1.5.5.
