### ISSUE TITLE
remove unused vendor files when downloading updated vendor_cdn 

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#176]
### Descriptive summary

updating local rdmo vendor files deletes old / unused files in directories `core` and `vendor` 

### Affects

Admins, Ops 

### Rationale

Once dependencies receive updates local vendor cdn must be updated and old / unused files must be deleted  

### Actual behavior

running `python manage.py download_vendor_files` will not delete old / outdated dependencies thus `python manage.py collectstatic` will copy also unwanted versions into `core` directory

### Expected behavior
Running  `python manage.py download_vendor_files` 
will  delete old files in `core` and `vendor` directories prior download of the new ones 
### Related work

https://github.com/rdmorganiser/rdmo/issues/172#issuecomment-581463995

**Comment by triole** [comment]
Fixed here: https://github.com/rdmorganiser/rdmo/issues/172#issuecomment-581463995.

Closing ticket.
