### ISSUE TITLE
"Last Changed" information in "My Projects" - Overview

### ISSUE THREAD

**Issue by evianders** [rdmorganiser/rdmo#196]
In the "My Projects" overview there is the creation date and time. For the user it would be nice to also know when it was changed the last time.

**Comment by evianders** [comment]
... and in case of more than one person working on/with the DMP also from whom it was changed.

**Comment by jochenklar** [comment]
Added in d37208e78135a914794e4f8ab549cb565d2ff602.

**Comment by jochenklar** [comment]
About the second part: we currently don't log who has changed a particular value. We might want to change this in the future.
