### ISSUE TITLE
Change position of project name to the right menu

### ISSUE THREAD

**Issue by evianders** [rdmorganiser/rdmo#197]
Answering the questions the projects name appears above the questions.
It might be a clearer view for the user, if the project name appears in the right menu on top. Above the progress-bar.
<img width="1194" alt="Bildschirmfoto 2020-05-18 um 11 22 00" src="https://user-images.githubusercontent.com/65225111/82210191-da57cb00-990e-11ea-857a-637751b76591.png">

**Comment by jochenklar** [comment]
This is connected to #199 I suggest we continue the discussion there.
