### ISSUE TITLE
Change in the navigation through questions: skip/proceed

### ISSUE THREAD

**Issue by evianders** [rdmorganiser/rdmo#198]
In the Navigation at the right side, there is "skip to  previous/next page". 
Below the recent question set also the "back", "skip", "save" and "save and proceed" options are available. 
For easier control the four buttons could be in the right menu and the "skip to  previous/next page" could be deleted.

**Advantage:** 
- no doubling of this functionality at the same page.
- avoids scrolling for longer question sets and/small screens.

**Comment by jochenklar** [comment]
We discussed this and finally added the same buttons but smaller to the sidebar in 8f96a1adcb9e7da9611378498168c667c6b17e50.
