### ISSUE TITLE
Change in the navigation through questions: Overview vs Navigation

### ISSUE THREAD

**Issue by evianders** [rdmorganiser/rdmo#199]
Overview and Navigation could be miss leading. 

There is "Back to project overview" above the "Overview", which, we think, is more the Navigation through the questions. 

Suggestion: 
- Delete the title "Navigation" and only have the "Back to project overview" link. 
- Change "Overview" to "Navigation", "Question sets", "Content"(My Favorite), or "Structure".  

<img width="1194" alt="Bildschirmfoto 2020-05-18 um 14 54 04" src="https://user-images.githubusercontent.com/65225111/82216129-c44f0800-9918-11ea-93bf-4d056612f609.png">

**Comment by jmfrenzel** [comment]
How about renaming "Projects' into 'My projects' in general. Thus,  "Back to project overview" would read  "Back to My Projects".

**Comment by jochenklar** [comment]
@jmfrenzel #200 and fixed just now.

**Comment by jochenklar** [comment]
Suggestion: Remove "Overview".

```
Navigation

Skip to previous question
Skip to next question

Back to my projects

General
  Topic
  ...
```

I think the table of contents doesn't need additional explanation.

**Comment by jochenklar** [comment]
![Screenshot_2020-08-27 example com](https://user-images.githubusercontent.com/1799675/91463406-a5530100-e88b-11ea-9588-6d4c722b5402.png)

Like this?

**Comment by jochenklar** [comment]
The Sidebar was reorganized in the RDMO 1.3 release.
