### ISSUE TITLE
Link/Naming to Projects overview

### ISSUE THREAD

**Issue by evianders** [rdmorganiser/rdmo#200]
In the overview of the single project, there is a button "Back to projects overview."
For better understanding for the user, it could be changed to "Back to 'My Projects'" or "My Projects".  

<img width="1194" alt="Bildschirmfoto 2020-05-18 um 15 18 26" src="https://user-images.githubusercontent.com/65225111/82218223-db432980-991b-11ea-8c7d-ebc1048b7431.png">

**Comment by jochenklar** [comment]
Changed in 883164440c9a94ed4e53fd3869f65817227fb90c.
