### ISSUE TITLE
Font Styles: sans serif only.

### ISSUE THREAD

**Issue by evianders** [rdmorganiser/rdmo#201]
We suggest only to use sans serif font only and change all headers which are now in serif fonts to sans serif. 
There is some style rule (and some other), e.g. not to mix these font styles, because of more clear structure.

**Comment by jochenklar** [comment]
Fonts can be changed by creating a Theme. I would be hesitant to make changes in the default theme at this point (but I am also the one who came up with the design choices in the first place :sunglasses: .
