### ISSUE TITLE
Easier change of standard text in templates

### ISSUE THREAD

**Issue by evianders** [rdmorganiser/rdmo#204]
If an existing template of a questions set in the RDMO catalog is going to be used, the creator of a new catalog can not change the grey standard introduction text or button text easily. 
Would be nice to have an introtext opportunity and button text while creating a question/question set.

![Bildschirmfoto 2020-05-12 um 16 49 49](https://user-images.githubusercontent.com/65225111/82292351-0c1e6f80-99ab-11ea-998e-5fabd3886dd0.png)

**Comment by jochenklar** [comment]
Would it be ok if the text can be customized for the whole instance and for each catalog. Then we could handle it using templates like the home page.

**Comment by jochenklar** [comment]
A seperate template was added in RDMO 1.2.
