### ISSUE TITLE
Separation of RDMO-original content from own definitions in "Options", "Domain" etc.

### ISSUE THREAD

**Issue by evianders** [rdmorganiser/rdmo#205]
For the definition of own options, domains (attributes), conditions etc. it starts to be crowded at these places. We would like to clean up at little bit and so it would be nice to have directories for the RDMO-original content and one or some directories for own definitions. 

**Background:** We use RDMO to create very project specific DMPs, where we even cannot use option sets from one project DMP for the other one. So it's getting quite confusing very quickly. 

**Advantage:** 
- more clear structure
- easier to find certain content
- (helpful for DMP-export to other institutions?)

**Comment by jochenklar** [comment]
After discussion: add more structure, e.g. in options. Ideas:

* filter by URI prefix
* static sidebar

**Comment by jochenklar** [comment]
URI prefix was added in 3098eeaa0b3f22d94be9982112ef7bda592bc2db, the static sidebar in 57786a093891f4d882be6617077ed18f9141c2c0.
