### ISSUE TITLE
Conditions form: Target (Option) selection list delivers insufficient information 

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#209]
### Descriptive summary

Creation and modification of conditions with 'Target (Options)' needs to provide more information to be eventually useful to the user .  

### Affects

Managers and Catalogers

### Rationale

The user must be able to identify the desired option as target to link it with the condition in the condition edit form. Providing the option text is not sufficient because it is not an unique string. In contrast, at the present (rdmo v1.0.6) the list has multiple entries "Yes" or "Other" ... Prepending the option's uid to the option text in that selection list would help. 

### Steps to reproduce 
(rdmo v1.0.6)

* login with a user having management privileges that allow to edit conditions
* go to /conditions form 
* create a new or edit an existing condition
* open the drop-down menu "Target (Option)"

**Comment by jochenklar** [comment]
Thanks, I will work on the management interfaces this summer and can implement the change.

**Comment by jochenklar** [comment]
Added in 7ab208922b318628a8765cdc2100bb3492ec9bf2.
