### ISSUE TITLE
Conditions seem to not be usable when referring to questions within questionsets that are marked as a collection

### ISSUE THREAD

**Issue by schmitzd** [rdmorganiser/rdmo#211]
I have not yet managed to formulate a condition in such a way that it is evaluated *individually* for each entry of a multi entry questionset. I think this is not possible. In conclusion this would mean that conditions can only be applied to non-collection based question(sets), i.e. at the project-wide level.

## Clarification
Suppose I have a question set asking for some rough format scope (text vs. data vs. multimedia) and presume that I want that to be answered for different datasets, i.e. I mark the corresponding question set as a "collection".

Now a second question set is introducing questions that depend on the selection of the rough formats, i.e. offering options for various text formats *and/or* data formats *and/or* media formats, depending on how the first question set was answered (multi value, i.e. the first question is also marked as a collection).

As long as we are at the project level (i.e. questionset is *not* a collection) it works as expected. But if we activate "collection" and answer the first question for different datasets differently, I get the sum of all detailed formats for each dataset (again the second question set is certainly again marked as "collection") at the second question. From what I see in where I define the conditions it seems obvious to me that there is no "link" to the right answer instance in the first dataset and I can't see how I could introduce it.

Could you confirm?

By the way, adding all detailed options set answer possibilities to a single question and using the conditions on the optionsets to show/not show has the same problem.

**Comment by schmitzd** [comment]
@jochenklar Could I get feedback on this?

**Comment by jochenklar** [comment]
Hi @schmitzd, sorry for the delay. Yes, it is not possible to use conditions with questionsets in a sensible manner. This is something we should work on, but so far nobody complained ... You are probably also the first, who tries to use conditions with optionsets.

We need to work on the "structured interview", since we are also unable to put sets in sets, which would be nice for e.g. a list of creators for each dataset. However, I think this will not happen soon (i.e. this year).

**Comment by schmitzd** [comment]
Thanks for the quick response!

But, I'm really puzzled. Our efforts in Aachen focus on *tailoring* of data management plan templates. And introducing conditions on questions and/or question sets is in this context very important in particular if you try to reduce the number of very individual question catalogs or additions to the domain.

Currently, we have this possibility but *not* at the level of individual datasets.

So this would definitively be a feature request. 
From the [report on the last workshop](https://www.forschungsdaten.org/index.php/Drittes_Community-Treffen)  I can see that you have been elected as head of software group and that you want to use GitHub issues for organization.

So what steps do I have to take to initiate this as a **feature request**?

**Comment by jochenklar** [comment]
This is certainly an important feature, but I cannot promise than stated above.

**Comment by jochenklar** [comment]
Conditions on questions should work now.
