### ISSUE TITLE
failing to install

### ISSUE THREAD

**Issue by 7048730** [rdmorganiser/rdmo#22]
Hello there,

thank you for your rdmo tool. I encountered an issue when I followed your installation guide for the windows environment (testing win10-64).

It fails to build certain base requirements:
`Failed building wheel for rcssmin`
`Failed building wheel for rjsmin`

I think you might want to add c++ compilers to the list of requirements and installation instructions.

>Microsoft Visual C++ 10.0 is required. Get it with "Microsoft Windows SDK 7.1": >www.microsoft.com/download/details.aspx?id=8279

**Comment by jochenklar** [comment]
Hi, thanks for the input, I will look into it.

**Comment by jochenklar** [comment]
fixed in f63c3fab42b2574239e007e584b3c66bde7e3b1e.
