### ISSUE TITLE
Missing translation functionality in search bar  placeholder 

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#229]
**Context** 

As of  cc8f6be a search bar placeholder string `placeholder="Search project title"` has been implemented in the following files.  

rdmo/projects/templates/projects/projects.html:23

rdmo/projects/templates/projects/site_projects.html:18

**Current behavior**
The string is not translated

**Expected behavior**
The placeholder string has translation functionality.

**Comment by triole** [comment]
Thanks for reporting. Fixed in https://github.com/rdmorganiser/rdmo/commit/5978c15f2f00536e32433c56b1592d6c398e5644
