### ISSUE TITLE
project_form: add translation fuctionality to submit buttons

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#230]
**Context** 

As of  cc8f6be the bootstrap buttons   
rdmo/projects/templates/projects/project_form.html:12
rdmo/projects/templates/projects/project_form.html:17  

do not provide translation functionality that can be alternated. 

**current behavior**
de locale translation of `rdmo/projects/templates/projects/project_form.html:12` is "Ansichten bearbeiten" which is not what  a user expects when the action is to save changes to views.   

de locale translation of `rdmo/projects/templates/projects/project_form.html:17` is "Projekt bearbeiten" which is not what  a user expects when the action is to save changes to tasks. 

 **expected behavior**
* implement i18n functionality for the buttons 
* change de translation of that buttons from "Ansichten bearbeiten" into "Ansichten aktualisieren"
* change de translation of that buttons from "Ansichten bearbeiten" into "Aufgaben aktualisieren"

**Comment by triole** [comment]
Thanks for reporting. Fixed in https://github.com/rdmorganiser/rdmo/commit/6664f4af18cb99b1539b9d55a5e8b59112b1f08f
