### ISSUE TITLE
Blue or red cross?

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#243]
Rdmo help refers to a "red cross" but in the ui the cross is of blue color. This affects the en locale only:

https://github.com/rdmorganiser/rdmo/blob/b87cb5b427f44d8ae53d260d9c30edaf08b5625a/rdmo/projects/templates/projects/project_questions_add_field_help.html#L5

while other locales, eg. de have been corrected already
  
https://github.com/rdmorganiser/rdmo/blob/f4305549df213282ec6e8728b258ea27ece5d91c/rdmo/locale/de/LC_MESSAGES/django.po#L2201

**Comment by triole** [comment]
Fixed here: https://github.com/rdmorganiser/rdmo/commit/9a3c5a66e872b1c7138c0fef48a6ea23289494eb#diff-1f4fdc52a9152b261626bb12e2da5ec5L2197. Will be in the next release.
