### ISSUE TITLE
Export as PDF fails

### ISSUE THREAD

**Issue by Bengrunt** [rdmorganiser/rdmo#274]
Hello,

I'm running a RDMO instance for our organization and I'm trying to make the export to pdf function work.
Our instance is deployed on an Openshift 3.11 cluster, the RedHat flavored Kubernetes distribution.

This run environment is a bit constrained security wise and docker containers shouldn't be run with elevated privileges for instance.
So far, I managed to make everything work except for this export to pdf function (all other exports work: latex, html, doc, etc).

I get this error:

```
Internal Server Error: /projects/27/views/1/export/pdf/
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 85, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/django/views/generic/detail.py", line 108, in get
    return self.render_to_response(context)
  File "/opt/venv/lib/python3.7/site-packages/rdmo/projects/views/project_view.py", line 80, in render_to_response
    return render_to_format(self.request, context['format'], context['title'], 'projects/project_view_export.html', context)
  File "/opt/venv/lib/python3.7/site-packages/rdmo/core/utils.py", line 174, in render_to_format
    pypandoc.convert_text(html, format, format='html', outputfile=tmp_filename, extra_args=args)
  File "/opt/venv/lib/python3.7/site-packages/pypandoc/__init__.py", line 101, in convert_text
    outputfile=outputfile, filters=filters)
  File "/opt/venv/lib/python3.7/site-packages/pypandoc/__init__.py", line 321, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "43" during conversion: b'Error producing PDF.\nThis is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2019/dev/Debian) (preloaded format=xelatex)\n restricted \\write18 enabled.\n\n'
```

Any idea how i could fix that?

Thanks!

**Comment by jochenklar** [comment]
Hi @Bengrunt, I have no clue. Maybe the views has something in it which prevents XeTex from compiling it. Can you try to compile the LaTeX export on you machine?

**Comment by Bengrunt** [comment]
Hi @jochenklar,

At first I investigated how the document is generated and thought it might be due to a permission issue when creating the temporary intermediate file but since all other exports use the same mechanism and work I'm not so sure anymore.
However, it might be good to be able to set which temporary folder is used for these intermediate files.

I see the python `mkstemp` function used in [this bit of code](https://github.com/rdmorganiser/rdmo/blob/4381470da7575d9f518035612c0e7c5dd2e2f34f/rdmo/core/utils.py#L178) has a `dir` option that specifies where to create the temporary files. Maybe an environment variable to set the value of `dir` could be added?
I believe it might be useful is situations where the filesystem is somewhat restricted and the application run with limited privileges (such as on a Kubernetes/Openshift cluster for instance).

I tried setting the `TMPDIR` environment variable, as explained in [mkstemp function documentation](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp) in my `local.py` script but to no avail.

```
'''
Export temporary directory location (used by tempfile.mkstemp())
'''
try:
    os.environ['TMPDIR'] = "/var/www/rdmo-app/tmpdir"
except KeyError:
    pass
```

Maybe I'm doing it wrong and the environment set by `local.py` is not passed on to RDMO?

So I'm out of options here. All exports work perfectly but PDF and I can't find why. :/ 
Any idea if I could increase pandoc verbosity somehow?

In the meantime, I asked my colleagues for a simpler DMP to test and see if that's an issue with something in the contents of the DMP text itself.

**Comment by sneumann** [comment]
The key part could be the "restricted \\write18 enabled." so I guess it is the latex / xetex configuration that needs modifying / fixing. Yours, Steffen

**Comment by Bengrunt** [comment]
Thanks for the reply.
I confess I don't have much experience configuring Latex distributions.

I tried with shorter/simpler DMPs in order to check if that was not a "content" issue as suspected initially but the result is the same.

Any idea how I could pass the `TMPDIR` environment variable to the `mkstemp` python function ? That's another idea I'd like to follow through. Since Openshift is much more restrictive on what the process can do or access it might also be the culprit.

**Comment by jochenklar** [comment]
Yes, I think this is the way to go, see also: this: https://stackoverflow.com/a/18280302. You should be able to set the `TMPDIR` environment variable in you docker compose or openshift config to some place where your process can write to.

**Comment by Bengrunt** [comment]
> 
> 
> Yes, I think this is the way to go, see also: this: https://stackoverflow.com/a/18280302. You should be able to set the `TMPDIR` environment variable in you docker compose or openshift config to some place where your process can write to.

So does that mean that the environment set with the `local.py` file is not available to RDMO ?

**Comment by jochenklar** [comment]
In `local.py` we usually don't environment variables, but Django configuration settings which are used in RDMO in the form `settings.FOO`. The mentioned `TMPDIR` environment variable is set in the environment of the running application, e.g. on the shell it would be something like `expoer TMPDIR=/some/path ./manage.py runserver`. The `mkstemp` function asks the system where it stores tempfiles (ususally `/tmp`), but you can tell the system (not RDMO) to use some other path, just for the RDMO context. I am not familiar with openshift, but it should have some means to set these enviroment variables.

**Comment by Bengrunt** [comment]
Thanks a lot @jochenklar that's just what I needed to know. Much clearer now.

I will try it this way and let you know if that works.

**Comment by jochenklar** [comment]
Hey @Bengrunt , did it work? (I am just cleaning up issues.)

**Comment by jochenklar** [comment]
Awesome, thanks for the update.
