### ISSUE TITLE
[BUG] As user, I want the progress bar to show the number of answered questions  for the selected question catalog

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#290]
As user, I want the progress bar to show the number of answered questions for the selected question catalog.

**Actual status**
* the progress bar display the number of answers for the project
* the numbers in the progress bar are not readable for **large** and **small** numbers of answered questions
![image](https://user-images.githubusercontent.com/30596226/102492850-8cf13700-4072-11eb-85ad-d097fabae498.png)

**Accepted status**
* [ ] the progress bar displays the number of answers only for the chosen catalog 
* [ ] the numbers in the progress bar are displayed in the center of the bar 

**Reference**
https://github.com/rdmorganiser/rdmo/releases/tag/1.4

**Comment by jochenklar** [comment]
Thanks for reporting, we will look into this.

**Comment by jochenklar** [comment]
This was fixed in RDMO 1.5.
