### ISSUE TITLE
[Bug] Display delete project icon for project owner, only 

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#291]
**Current status**

The delete  project icon is displayed to all roles. Only owners get forwarded to the delete project project dialog. Al other roles receive an 403.

**Desired status**
Delete project icon is displayed for project owner, only.

**References**
* rdmo-v1.4
* reproduced on rdmo.aip.de 2020-12-21

**Comment by jochenklar** [comment]
This was fixed in RDMO 1.5 ().
