### ISSUE TITLE
Improve many to many relations

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#300]
"Im Bearbeiten-Menü einer Frage wäre eine Suchmöglichkeit im Reiter "Optionensets" sehr hilfreich, um ein bestimmtes Optionenset zu finden. Es wäre außerdem gut, wenn die Liste alphabetisch geordnet werden könnte. Auch ein Link, um von dieser Liste direkt zur betreffenden Option zu kommen, um diese zu bearbeiten / zu kopieren, wäre sehr hilfreich."

**Comment by MyPyDavid** [comment]
das gibt es jetzt oder?

can be closed by [2.0.0](https://github.com/rdmorganiser/rdmo/releases/tag/2.0.0)
