### ISSUE TITLE
Optionset visibility

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#301]
- Eine Übersichtsanzeige im Fragenkatalogmenü, welche Optionensets in einem bestimmten Fragenkatalog verwendet werden
- Eine Übersichtsanzeige im Optionsmenü, welche Optionensets nicht mit einem Fragenkatalog verknüpft sind

**Comment by MyPyDavid** [comment]
this should also be covered with the new UI of the [2.0.0](https://github.com/rdmorganiser/rdmo/releases/tag/2.0.0) release
can be closed?
