### ISSUE TITLE
TemplateSyntaxError: drilldown_tree_for_node-Tag

### ISSUE THREAD

**Issue by m6121** [rdmorganiser/rdmo#309]
After updating to the latest version (1.5), we are experiencing the following issue when opening a project, i.e. `https://<instance url/projects/<project id>`

> **TemplateSyntaxError: drilldown_tree_for_node-Tag needs either three, seven or eight arguments**
> In template /vol/ve/lib/python3.7/site-packages/rdmo/projects/templates/projects/project_detail_header.html, error at line 51

Currently, we are using custom css at:

- static/core/css/variables.scss
- static/core/css/base.scss
- static/core/css/footer.scss

and templates at: 

- templates/core/base.html
- templates/core/base_head.html
- templates/core/base_navigation.html
- templates/core/base_footer.html

What might be the reason for this error?

**Comment by jochenklar** [comment]
Hi @m6121 , did you run `./manage.py migrate` after updating? The templates should be fine.

**Comment by jochenklar** [comment]
ok, can you tell me what the output of `pip freeze | grep mptt` is?

**Comment by m6121** [comment]
Thanks a lot for the fast response!
```
$ pip freeze | grep mptt
django-mptt==0.10.0
```

**Comment by jochenklar** [comment]
Bingo! Our version pinning in https://github.com/rdmorganiser/rdmo/blob/master/requirements.txt is not ok. `django-mptt` should be at `0.11`. You can fix this using `pip install --upgrade django-mptt`, but we will need to publish a new version tomorrow anyway.

**Comment by jochenklar** [comment]
And thanks for testing our Release so fast!

**Comment by m6121** [comment]
That solved the problem. Thank you very much for the very fast investigation of this issue.
