### ISSUE TITLE
[bug] project catalog not displayed in sidebar

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#310]
**actual behavior** 
'Answer questions' dialog: project catalog not displayed in sidebar

**desired behavior** 
'Answer questions' dialog displays project catalog in sidebar

**Steps to reproduce**
1. login to rdmo running rdmo [v1.5.0](https://github.com/rdmorganiser/rdmo/releases/tag/1.5.0) or [v1.5.1](https://github.com/rdmorganiser/rdmo/releases/tag/1.5.1)
2. click on  a project or create a new one 
3. clock on  'Answer questions' in the sidebar
4. find empty 'Catalog' entry in the sidebar 

**reproduced** 
rdmo demo on https://rdmo.aip.de 2021-02-24 13:43 h

**Comment by jochenklar** [comment]
Hi @jmfrenzel , I think this is a problem with the browser cache.

**Comment by jmfrenzel** [comment]
Reproduced the behavior with rdmo (local dev install) and empty browser caches

**Comment by jmfrenzel** [comment]
Being used in` rdmo/projects/templates/projects/project_questions_overview.html`I wonder where `service.catalog.title` is being defined? 

Seems to me that it has been removed 
https://github.com/rdmorganiser/rdmo/commit/5461b0832f6091c3efe458470b1f92cfb1cb05b7#diff-0eb03278982cc4c0a524aca6b4651e0602eca6d298b9d96251410a4201250938L68

**Comment by jochenklar** [comment]
Yes, this was changed. I added a list of all changed templates to the release page: https://github.com/rdmorganiser/rdmo/releases/tag/1.5. It was not in the mail, though. The field is now `service.project.catalog.title`. I think we had two things here, the template in your app and the browser cache on rdmo.aip.de.

**Comment by jmfrenzel** [comment]
I use the vanilla template of rdmo rdmo/projects/templates/projects/project_questions_overview.html 

This PR #311 solves this issue

**Comment by jochenklar** [comment]
Sorry, I was not reading carefully. I thought you mean the Navigation in the sidebar. Thanks for the PR. I need vacation :neutral_face: .
