### ISSUE TITLE
Migration fails when upgrading to 1.5.3

### ISSUE THREAD

**Issue by FabianHamm** [rdmorganiser/rdmo#315]
Hello,

I just tried to upgrade our RDMO installation from 1.3.0 to 1.5.3. However when running the database migration `python manage.py migrate` i get the following exception:

> (env) [rdmo@rdmo rdmo-app]$ python manage.py migrate
> Operations to perform:
>   Apply all migrations: accounts, admin, auth, authtoken, conditions, contenttypes, domain, options, projects, questions, sessions, sites, tasks, views
> Running migrations:
>   Applying projects.0046_project_mptt...Traceback (most recent call last):
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
> psycopg2.errors.ObjectInUse: cannot CREATE INDEX "projects_project" because it has pending trigger events
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "manage.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/core/management/base.py", line 364, in execute
>     output = self.handle(*args, **options)
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
>     res = handle_func(*args, **kwargs)
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 234, in handle
>     fake_initial=fake_initial,
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
>     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
>     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 247, in apply_migration
>     migration_recorded = True
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 110, in __exit__
>     self.execute(sql)
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 137, in execute
>     cursor.execute(sql, params)
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/srv/rdmo/rdmo-app/env/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
> django.db.utils.OperationalError: cannot CREATE INDEX "projects_project" because it has pending trigger events

I am using PostgreSQL 10.6. Any hints / help is appreciated.

Thanks

**Comment by jmfrenzel** [comment]
We ran into a very similar problem while upgrading rdmo v1.4 to rdmo-v1.5.3.
Reason was that we were using different versions of PostgreSQL server v10.x and client v12.x. In PostgreSQL major release 12x some psql features were removed. 

The upgrade ran through after upgrading to PostgreSQL version 12   

@jochenklar reproduced this

**Comment by jochenklar** [comment]
Workaround (not for the faint of heart, backup your database!):

1) Comment out https://github.com/rdmorganiser/rdmo/blob/master/rdmo/projects/migrations/0046_project_mptt.py#L63 in your installed version of RDMO, e.g. in `/srv/rdmo/rdmo-app/env/lib/python3.6/site-packages/rdmo/projects/migrations/0046_project_mptt.py`. Path may change with your setup and Python version.

2) Run `python manage.py migrate` to migrate the database.

3) Open a python shell with `python manage.py shell_plus`.

4) Run `Project.objects.rebuild()` in this shell.

**Comment by jochenklar** [comment]
RDMO 1.6 will use Django 3.2 so this will not be a problem anymore.

**Comment by jochenklar** [comment]
I think we can close this now.
