### ISSUE TITLE
"View answers" does not show all answers

### ISSUE THREAD

**Issue by schmitzd** [rdmorganiser/rdmo#318]
Unfortunately, the "view answers" feature is not working properly in that it simply does not show all answers that you can access in "Answer questions".

The reason seems to be the empty content of this if clause:
https://github.com/rdmorganiser/rdmo/blob/42eb42a9c20955625dd48107556599c02091a95d/rdmo/projects/templates/projects/project_answers_tree.html#L15

This is for a `questionset` marked as `is_collection = True`, nothing happens.

Note that the original RDMO catalog also sets this flag for question sets, e.g. :
https://github.com/rdmorganiser/rdmo-catalog/blob/28cdad53c2056455b6b6810b8a2673b4ec391afe/rdmorganiser/questions/rdmo.xml#L671

That could never have correctly worked could it?

**Comment by schmitzd** [comment]
@jochenklar You deleted this code on Feb 10th, see https://github.com/rdmorganiser/rdmo/commit/5461b0832f6091c3efe458470b1f92cfb1cb05b7#diff-9356f5993e9a1d47e7335a061d435ca32e29d7a222e67e3b1017685a360bc8e4

Erroneously, I presume...

**Comment by torsten-rathmann** [comment]
I also encountered the issue for questions that are collections.

**Comment by jochenklar** [comment]
Hi @schmitzd, @torsten-rathmann, I will look into it.

**Comment by jochenklar** [comment]
I think I removed the block to play around with database optimizations and never put it back. I fixed it in https://github.com/rdmorganiser/rdmo/pull/320. We will release a new version this week. Thanks!
