### ISSUE TITLE
Severe BUG: Erroneous database entries are created that prevent correct answer rendering

### ISSUE THREAD

**Issue by schmitzd** [rdmorganiser/rdmo#323]
There are circumstances that cause database entries to be written where the `attribute` field is empty.
Further on, you loose the piece of information that you have entered and assumed to have saved!
Eventually, this leads to a server error (500) when trying to call `View answers`.

# How to reproduce
1. Create a new project using the standard RDMO catalog.
2. Enter "Answer questions" and navigate to the area "Data usage / Interoperability"
3. Click here "Add dataset". **Note** The problem only occurs if the question that you are about to answer is marked as `is_collection=True` while you click on "add dataset".
4. In the database you get two new entries for the attributes `project/dataset/id` and `project/dataset/interoperability`
5. If you now check at least one of the items and click on `save` the database entries will *not* get the value `project/dataset/interoperability` in the *attribute* field but an empty value that causes all the mess.
6. Returning later to this question you will no longer find your previous answers. But then you are able to enter data and now they are saved correctly.

Unfortunately, in the catalogs we designed ourselves nearly all *dataset* related questions start with a question that can have multiple answers, i.e. where `is_collection=True` is set :-(((.

This is: Currently, I'm regularly checking the database of our productive system on the search for these values and simply delete them since I hardly have a chance to find out, which question was tried to be answered.
Only then people are again able to use `View answers`. But all of them have to manually add the data that they lost.

@jochenklar Sorry to bother you again, but for the last two days I'm deleting erroneous values in the database to allow people to produce the PDFs of their DMPs that they need to hand in on time. It would really be brilliant, if that bug could also be fixed for 1.5.5! Thanks in advance!

**Comment by jochenklar** [comment]
Hi @schmitzd , thanks for reporting. I can reproduce the bug, kind of. In my case the value is created with the correct attribute, but with no option, even if I check the first checkbox. I will look into it, today.

**Comment by jochenklar** [comment]
The error only occurs when I select an item which is not the first item :exploding_head:

**Comment by jochenklar** [comment]
I think it only affects the checkbox widget, can you confirm this?

**Comment by schmitzd** [comment]
I can confirm, that we use the checkbox widget intensively, so yes, this is very probable.

**Comment by schmitzd** [comment]
And yes, also in my cases, if I only check the first item, the problem does not occur. But if I check more than the first, then I still get erroneous entries for these additional items.

**Comment by jochenklar** [comment]
Ok, I think I have it: right now, when you create a new set a value is created for the `id` attribute and for each question. The latter was needed when there is no `id` attribute. I think this is used by no one and if, there is only a minor inconvenience (I hope). So I removed this creating of values and added the initialization of the checkboxes, which was missing.

If you have a test system you can try the branch with the fixes using:

```
pip install git+https://github.com/rdmorganiser/rdmo@fixes
```

Thanks again for the input. These are tricky bugs bot somehow we need to find them.

**Comment by jochenklar** [comment]
I also fixed the 500 when attributes are missing: https://github.com/rdmorganiser/rdmo/commit/b31cde30354484779fdcc96c241ed141a2fc67d8

**Comment by schmitzd** [comment]
Thanks for the quick response! I ask someone to look in to the fixes you provided!

**Comment by schmitzd** [comment]
I could try it out and the error indeed does not occur on the test system. Great!
Also regarding the "missing attribute" does no langer harm the "View answers" feature. Another great!
