### ISSUE TITLE
registration link does not work on landing page

### ISSUE THREAD

**Issue by MSpenger** [rdmorganiser/rdmo#325]
With release 1.5.4 the "registration" link in the right sidebar does not work. Instead of linking to /account/signup/ it links back to the landing page.

![grafik](https://user-images.githubusercontent.com/11438980/112121230-4e15d480-8bbf-11eb-8518-340f134a3345.png)

**Comment by jochenklar** [comment]
Yes, thanks for reporting, we already fixed this in https://github.com/rdmorganiser/rdmo/commit/0f504cb183af8c5135190ee52baa47289ac42d06 and will release 1.5.5 soon.
