### ISSUE TITLE
AUTH_USER_MODEL setting not supported in RDMO

### ISSUE THREAD

**Issue by maweber** [rdmorganiser/rdmo#337]
Currently rdmo uses the User model from django.contrib.auth.models . E.g. in foreign key relations.

This prevents to use a custom User model, that can be set via AUTH_USER_MODEL in django settings,
compare: https://docs.djangoproject.com/en/dev/ref/settings/#auth-user-model

Replacing occurrences of django.contrib.auth.models.User with AUTH_USER_MODEL would provide
the option to use a custom user model, without preventing the option to use the base user model.

**Comment by maweber** [comment]
#349

**Comment by jochenklar** [comment]
Will be part of RDMO 1.6.
