### ISSUE TITLE
Silent invite with missing user leads to server error

### ISSUE THREAD

**Issue by jsubhi** [rdmorganiser/rdmo#339]
## Summary
When trying to invite a member to a project silently using the "Add member silently"-Option a 500 Server error occurs if the user field is left blank.

## Steps to reproduce
- Open a project's /membership/create page
- Leave user-field blank
- Check option "Add member silently"
- Klick "Invite member"

## Expected behavior
There should be an an error message indicating that the username is missing - as is the case when the  "Add member silently" is not checked.

## Actual behavior
500 Server Error

## Environment
    pip show rdmo 1.5.5
    python –version 3.6.9
    python -m django –version 2.2.20
    mysql -V Ver 14.14 Distrib 5.7.33

**Comment by jochenklar** [comment]
Hi @jsubhi, thanks for reporting this will be fixed in the next release.
