### ISSUE TITLE
unclear grouping of fields in the admin dashboard

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo#342]
![grafik](https://user-images.githubusercontent.com/37865804/121650133-8ed40a00-ca99-11eb-8c9e-c29e0f43dcad.png)

Hallo,
in the admin view are the user-related data divided between four different chapters - is there a reason for that?
VG

**Comment by jochenklar** [comment]
Those are different Modules (or Django-Apps), from top to bottom:

* rdmo.accounts
* django-allauth
* django-rest-framework
* Django
