### ISSUE TITLE
Sicherheit bei der Authentifizierung / Safety by signup

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo#343]
Hallo,

da eine RDMO-Instanz für "interne" und "externe" Nutzer zugänglich ist, wären zusätzliche Optionen wünschensvert:

* Eine Identitätskontrolle für neuregistrierte Nutzer (Captcha), um Bot auszuschließen
* Eine Single-Sign-In-Option für institutsinterne Nutzer (SAML2)

**Comment by jochenklar** [comment]
Für den ersten Pukt sehe nicht so richtig die Notwendigkeit. Man kann auch erstmal Email validierung verlangen. Das zweite wäre schöne, aber sehr aufwendig. Dann könnte man auch gleich Shibboleth drüber machen.

**Comment by janstrassburg** [comment]
E-Mail validierung wäre ein guter erster Schritt. Ist das denn schon implementiert? Bei uns haben sich schon einige russische Bots Konten angelegt. Es wäre schön das verhindern zu können ...

**Comment by jochenklar** [comment]
Ja, mit `ACCOUNT_EMAIL_VERIFICATION = 'mandatory'`, dann sollte man sich erst einloggen können wenn man die Email best
tigt hat.

**Comment by jochenklar** [comment]
Inzwischen kann man RDMO auch mit Keycloak betreiben: https://github.com/rdmorganiser/rdmo/issues/456
