### ISSUE TITLE
Missing "Send" button? 

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#344]
The send task form is missing an action  ("Send") button.  

![Screenshot_2021-06-15_14-50-41](https://user-images.githubusercontent.com/30596226/122055740-38dcca80-cde9-11eb-93a8-b521fe6ec443.png)

**Reference**  
rdmo Version 1.5.5 @ rdmo.aip.de

**Comment by jochenklar** [comment]
Hi @jmfrenzel , you need to configure `EMAIL_RECIPIENTS_CHOICES` and/or `EMAIL_RECIPIENTS_INPUT`. See also https://rdmo.readthedocs.io/en/latest/configuration/email.html#send-tasks-via-email.

**Comment by jmfrenzel** [comment]
Ok. If that email function is not configured, the link to the end form
should not be displayed.

**Comment by jochenklar** [comment]
Ok, I looked into it and there is a `PROJECT_SEND_ISSUE = True` setting which we could default to `False`. This would be the cleanest solution.

**Comment by jmfrenzel** [comment]
Sounds good to me

**Comment by jochenklar** [comment]
Done.
