### ISSUE TITLE
Update available views when changing catalog of a project 

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#345]
Changing of the project question catalog should also update the views that are available according to the actual (new) catalog. 

**Current behavior**  
Changing a catalog of a project does not automatically update the list of views that are associated with that catalog. 
**Desired behavior**  
Changing a catalog of a project automatically updates the list of views that are associated with that catalog.

**Comment by jochenklar** [comment]
Hi @jmfrenzel , well, its the other way around: Views have catalogs configured and are not displayed if the catalogs don't match. I had some reasons to make views (and tasks selectable), but I cant remember. Lets discuss later.

**Comment by m6121** [comment]
We also had this issue: After updating a view and restricting its use to some catalogs (previously the view was availble in all catalogs), we also wanted to change the existing projects accordingly. As an example, assuming the following:

Catalog: CA, CB
View: VB
Project: pCA

VB was previously configured for both catalogs and is now restricted to CB. The existing project pCA however has the view VB still in its list.

We would like to automatically remove views from existing projects according to their configuration in the management interface.
