### ISSUE TITLE
Sorting and filter functions for "View all projects" window

### ISSUE THREAD

**Issue by Freund-J** [rdmorganiser/rdmo#355]
As a site manager, there is the possibility to display all projects of the site when clicking on "View all projects on ...". It would be good to have more filter and sorting options for this view. Specifically, the following features would be desirable:

- Adding an additional column containing the owner of each project
- Function to sort the projects by name, date created, date last changed and owner name
- Function to filter the projects by date created (or part of the date, e.g. showing all projects created in 2021), date last changed and owner name (currently the search function only searches the project titles)
- Adding a counter which shows the total number of projects that exist on the site
- Perhaps adding an additional counter which shows the number of projects which are currently displayed (after filters have been applied)

**Comment by jochenklar** [comment]
The question is here if we create a javascript page and use the API or if we use a classical pagination with URL parameters.

**Comment by jochenklar** [comment]
Will be released in 2.2.0
