### ISSUE TITLE
Improve backend for catalogue design: Assigning questions to categories

### ISSUE THREAD

**Issue by YvanaGlasenapp** [rdmorganiser/rdmo#361]
Assigning custom questions to an existing category is, let´s say, sub-optimal. Show categories as an expandable tree rather than a confusing, unsearchable and unfilterable list of lengthy url.

**Comment by jochenklar** [comment]
This boils down to have a better visual representation of elements in foreign key or many 2 many fields.

**Comment by MyPyDavid** [comment]
the new management interface ([2.0.0](https://github.com/rdmorganiser/rdmo/releases/tag/2.0.0)) allows this , questions can be assigned to pages.
In the nested catalog view, questions can be copied and edited.
Can this be closed @YvanaGlasenapp?

**Comment by YvanaGlasenapp** [comment]
Yes, thank you!
