### ISSUE TITLE
Improve backend for catalogue design: Create and edit option sets

### ISSUE THREAD

**Issue by YvanaGlasenapp** [rdmorganiser/rdmo#362]
When designing a custom catalogue, you cannot directly add the answer options to a new question (or alter the existing ones). Instead you have to go to "options" first and create or edit an option set there, then go back to the question, switch to the "option set" tab and scroll through a list of url to find the respective option set. That´s far from being either intuitive or effective. It should be possible to create or edit option sets directly from the "Question" page. And the eligible option sets should be shown in a tree layout, not as a list of url.

**Comment by MyPyDavid** [comment]
this should also be covered with the new UI of the [2.0.0](https://github.com/rdmorganiser/rdmo/releases/tag/2.0.0) release
can be closed?
