### ISSUE TITLE
Indistinguishable titles:  rdmo "Answering questions | Overview  

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#363]
### Overview 
The following titles (German locale) are to long to be fully displayed in  rdmo "Answering questions | Overview " at current css. 

* Fragenset Urheber- oder verwandte Schutzrechte I rdmo/legal-and-ethics/intellectual-property-rights-yesno

* Fragenset Urheber- oder verwandte Schutzrechte II rdmo/legal-and-ethics/intellectual-property-rights-dataset → project/dataset 

* Fragenset Urheber- oder verwandte Schutzrechte Kosten rdmo/legal-and-ethics/intellectual-property-rights-costs

### Rationale
User can not discriminate between question sets 

### Expected behavior
I expect to read the full title (German locale), which shold be shown when hovering over that title, or rdmo adapts the css or allows multiple lines per title.

### Actual behavior
Browser window dimension >=1200 x xyz 

Übersicht

    Allgemein
    Inhaltliche Einordnung
    Technische Einordnung
    Datennutzung
    Metadaten und Referenzierung
    Rechtliche und ethische Fragen
        Recht allgemein
        Personenbezogene Daten
        Datenschutz
        Sensible Daten
        Weitere sensible Daten
        Sensible Daten Kosten
        Offizielle Genehmigung
        Urheber- oder verwandte Schutzrec...
        Urheber- oder verwandte Schutzrec...
        Urheber- oder verwandte Schutzrec...
    Speicherung und Langzeitarchivierung

Browser window dimension 992< x <1120 x xyz

      Urheber- oder verwandte Sc...
      Urheber- oder verwandte Sc...
      Urheber- oder verwandte Sc...

Browser window dimension
Further problems <340 x xyz 

### Steps to reproduce the behavior
1. create a project (rdmo catalog)
2. go to "Answering questions"
3. change to German locale
4. click  `Rechtliche und ethische Fragen`
5. Change bowser window dimension, e.g. using Firefox Developer tools (F12)
![image](https://user-images.githubusercontent.com/30596226/131103858-d0a9634f-a2fa-41a1-aa86-409673616eb3.png)

**Comment by jochenklar** [comment]
https://github.com/rdmorganiser/rdmo/issues/479

**Comment by jochenklar** [comment]
Actually the same as https://github.com/rdmorganiser/rdmo/issues/346

**Comment by jochenklar** [comment]
Will be part of RDMO 2.2.0.
