### ISSUE TITLE
Highlighting the active tab

### ISSUE THREAD

**Issue by YvanaGlasenapp** [rdmorganiser/rdmo#366]
When you fill out the details for your datasets, the content field clears after you click "save and proceed". This can be confusing, because at first you don't know that now you see the field of the next dataset-tab. It seems like the details you just typed in where deleted. Suggestions for improvement:

- Adapt the button "Save and proceed" to "Save and proceed to next dataset"
- Highlight the active tab, e.g. by a different background colour. It is otherwise easy to confuse which dataset is being edited.

**Comment by jochenklar** [comment]
The dataset don't cycle anymore, but the user changes to the next page (for the same dataset), so this problem should be solved now.
