### ISSUE TITLE
Conditions on dataset (collection) level

### ISSUE THREAD

**Issue by hgoerzig** [rdmorganiser/rdmo#370]
In a project the different dataset types might need different follow-up questions. If I am correct the conditions are project wide, if this is the case are there any thoughts to apply them on collections or reasons against it? As I see the information to do so is in the database.

**Comment by jochenklar** [comment]
Hi @hgoerzig , this will be possible in the new version 1.6 which we will release soon ... There is a release candidate for testing available. Conditions will be checked using the answers for a particular dataset only.

**Comment by jochenklar** [comment]
Indeed this was introduced in RDMO 1.6.
