### ISSUE TITLE
[Bug] Update catalog with empty text 

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#371]
Updating an existing catalog with an empty help text field will not remove existing text in that entry 

Steps to reproduce  

1. Import an catalog from an xml file into rdmo
2. Edit the same catalog file which outside of rdmo (with a text editor) and replace the content of a help text entry `<help lang="de">Lorem ...</help>` with an empty `<help lang="de"/>` or `<help lang="de"></help>`
3. Import the edited (with empty entry)  catalog file 
4. Select the catalog in the management UI and brows to the field which was replaced with an empty entry
5. Find the field containing the old content

**Comment by jochenklar** [comment]
Fixed.
