### ISSUE TITLE
Concurrent work on a checkbox question leads to inconsistent database

### ISSUE THREAD

**Issue by schmitzd** [rdmorganiser/rdmo#380]
If two people (or one within one browser) work simultaneously work on a checkbox question (and check the same item) both inputs will arrive in the database.
While "View answers" shows both answers, "Answer questions" will *not* show **any value** for the given checkbox. I.e. the user thinks the question is not yet answered and will thus add a third, fourth, ... value, never getting to the point that the answer becomes visible at "Answer questions".

I noticed that the other controls react differently. For example, if you add a title in parallel, the "Answer question" will show edit fields for both entries (looks strange but at least the user has access to this and is thus able to "repair" it).

# How to reproduce

1. Create a new project using the standard RDMO catalog.
2. Enter "Answer questions" and navigate to the area "Data usage / Interoperability"
3. Click here "Add dataset". 
4. Open a second browser window at the same question.
5. Check the same item in both windows (additional info in the additional input field can deviate).
6. Hit "save" or "save and proceed" in both windows. There is no need to perform this simultaneously. Important is only that both opened the page in the same state (and not one after the other).
7. Both value will enter the database. Can be checked at "View answers".
8. Return to the question in "Answer questions" and you will see that the corresponding item is *not* checked (and in contrast to other controls does not appear twice).

@jochenklar  Not really related to #323 but it concerns the same - obviously problematic - control :-)

**Comment by schmitzd** [comment]
Minor addition: Indeed with have serveral of such entries in our database, that I have simply cleaned up manually.
Typically the creation dates deviate only within 1 to 5 seconds. Further on due to a discussion with the users in our case they did not *work* concurrently neither do they have two browser windows to the same question open. Instead we assume that the server sometimes seems to be a little bit slow (for whatever reasons) so people hit the save button twice and *thereby* create the double entries. But unfortunately, I was not able to reproduce this reliably. Yet for our case we are sure that this is the reason so that we are not able to solve it by organisational measures such as "don't work in parallel" or "do not open a plan twice".

By the way: We are on the latest stable release 1.5.5

**Comment by jochenklar** [comment]
Hi @schmitzd , thanks for reporting. I can reproduce the problem ... somehow with my test catalog. I get the same behavior for regular fields, which makes sense since the values are just created both with the same collection_id.

Other things I learned:
* If you have two id valiues for the same set_index the first wins (which is good.)
* The new autosave option makes it even weirder.

**Comment by jochenklar** [comment]
Ok I fixed it, kind of. The front-end checks for every option if a value for this option exists, and before it only checked the box if exactly one value was found. However if you uncheck the field, the other value will stay so you need to uncheck it again.

I think we need to do something about simultaneous edits in the next release.

**Comment by schmitzd** [comment]
@jochenklar Thanks for your quick reaction.

Beyond the agreed need to cope with simultaneous edits I see still problems with your proposed solution.

Indeed now a value is shown where none was visible before.
But this certainly also means that the user will not see the need to correct something here (as opposed to a double title field in case of more than one value).
These people might only wonder about a duplicate answer in the "View answer" sections. But they will have no clue how they can repair this. At least for RDMO administrators it would then be possible to fix this without fiddling with the admin interface or the database directly.
But even they need to reload the page after saving to find that the previously unmarked item is still checked due to another value in the database.

And one more thing to consider: The interface allows to check a box *and* add a text value that is also stored in this attribute value. Note that the textual values of double entries can differ! While you can see them in the "View answers" section you only see one value at a time in the "Answer question" section.
An administrator as well as a user might have difficulties to remember the value just deleted if the remaining value accidentially is not the one intended to be kept... I know that is a bit "constructed". I was lucky that in my cases the additional text values were also identical but in particular with simultaneous additions that might not be the case, so cleaning up might not be straightforward.

Anyway, I think it is indeed the best idea to avoid arriving at such a situation at all. So looking forward to your ideas to cope with simultaneous edits.
