### ISSUE TITLE
LDAP users cannot delete their RDMO account

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#384]

**Comment by m6121** [comment]
Hi @jochenklar,

I worked on this issue which seems to work if the `user.check_password()` function is replaced by Django's `authenticate()` function at this line: https://github.com/rdmorganiser/rdmo/blob/master/rdmo/accounts/utils.py#L52

However, when using LDAP the PROFILE_UPDATE is deactivated which requires the remove view to be linked somewhere else than in the profile update view, e.g. into the main navigation. What do you think is the best place to put a link for the account removal into in the rdmo theme?

I will provide a PR that implements these adjustments.

Best regards
Max
