### ISSUE TITLE
Nonbreaking spaces break RDMO catalog

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo#393]
The presence of the HTML code `&nbsp;` prevents RDMO 1.5.5 from importing the catalog [rdmo.xml](https://github.com/rdmorganiser/rdmo-catalog/blob/1991a1d376d25f3eb3758477b2cda3cd99c54671/rdmorganiser/questions/rdmo.xml#L71), despite it being acceptable from the Django syntax.

Error message in rdmo.log:

> [2021-10-19 15:18:47,093] ERROR rdmo.core.xml: Xmlparsing error: undefined entity: line 71, column 76
> [2021-10-19 15:18:47,093] INFO rdmo.management.views: Xmlparsing error. Import failed.

Other HTML codes such as `&quot;` do not break the code in a similar way.

The nonbreaking space is actually required by French orthographic rules before the question mark and inside the quotes.

Is there an easy solution? How does it work in the ewer RDMO 1.6?

**Comment by jochenklar** [comment]
Hi @Zack-83 , `&nbsp;` needs to be escaped as `&amp;nbsp;` since the input/output format is an XML file.
