### ISSUE TITLE
XML Export of project

### ISSUE THREAD

**Issue by skelligan** [rdmorganiser/rdmo#40]
When exporting a project as XML, all answers of all projects using the same questions catalog are included in the XML file. Is that intended behaviour or a bug?

**Comment by jochenklar** [comment]
This is indeed a bug. Thanks for reporting.

I already fixed it in 808ca3dd48048c9dd0a2c6761f57a523cca2e9cd.

**Comment by skelligan** [comment]
Great, thanks.
