### ISSUE TITLE
[BUG] domain export contains duplicates 

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#404]
Export of a domain in xml format from the management interface > domain results in duplicate entries.

The number duplicate entries per attribute increases with the depth in the tree, i.e. parent, grandparents, ... 

This bug most likely identical to #126  (fixed via ) but got reintroduced via https://github.com/rdmorganiser/rdmo/commit/73ecedf08b8017e9ac45a69871e54c44f5ee37f3

see [diff](https://github.com/rdmorganiser/rdmo/commit/73ecedf08b8017e9ac45a69871e54c44f5ee37f3#diff-ff7574d7a43eefb88c27bfdaca347359fc1380acfb53fc54c3e7ffe4438e8561)

Ref:
* #126
* 01346ba
* https://github.com/rdmorganiser/rdmo/commit/73ecedf08b8017e9ac45a69871e54c44f5ee37f3

**Comment by jochenklar** [comment]
Thanks! I will try to fix this asap.

**Comment by jochenklar** [comment]
Fixed in `dev`.
