### ISSUE TITLE
Import should not crash when questions don't have attributes

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#414]
fix here: https://github.com/rdmorganiser/rdmo/blob/master/rdmo/projects/mixins.py#L35

**Comment by MyPyDavid** [comment]
I have reproduced a similar error at import of a project.
> AttributeError at /projects/import/
> 'NoneType' object has no attribute 'uri'  

at `if question.attribute.uri not in questions:`

Maybe a fix in [projects/mixins.py#L35](https://github.com/rdmorganiser/rdmo/blob/master/rdmo/projects/mixins.py#L35) with an extra if statement?
```python
for question in queryset:
    if question.attribute: # fix?
        if question.attribute.uri not in questions:
           questions[question.attribute.uri] = question

```
