### ISSUE TITLE
Adding co-workes to project is not possible anymore

### ISSUE THREAD

**Issue by KatjaMarciniak** [rdmorganiser/rdmo#416]
Hello, 
after the update of RDMO to version 1.7.0 we (at the BBAW) have a problem with invitations. 
Users who are already part of a project (as „manager“) can’t add other co-workers to their project anymore. 
Did this changed behaviour occur in other institutions as well? Do you know, what might be the reason and how it can be fixed?

**Comment by jochenklar** [comment]
Hi @KatjaMarciniak , actually only owners can invite new members, otherwise managers could invite new owners, which then could make them owners themselves. Out role system is not sophisticated enough to prevent that. How old was your last version? It should be like this for some time.

**Comment by KatjaMarciniak** [comment]
Thank you so much for this explanation. It is true that a few versions have been skipped, but now we are up to date again. :)
