### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#42]
A user should be able to delete his/her account, when it is not longer needed.

**Comment by leucoryx** [comment]
easier deletion: just with one click

**Comment by leucoryx** [comment]
Also deletion button for the domain, questions, etc. goal: to be able to have a empty installation again

**Comment by triole** [comment]
User profile deletion button is being developed in branch https://github.com/rdmorganiser/rdmo/tree/remove_profile

**Comment by triole** [comment]
Already merged into master.
