### ISSUE TITLE
 Highlight sections with missing answers

### ISSUE THREAD

**Issue by m6121** [rdmorganiser/rdmo#424]
During the iterative answering of DMPs it would be very helpful if the sections with missing answers are highlighted. Especially during the answering of long DMPs that are almost complete (e.g. 27 of 30 questions in the progress bar) it might be helpful for users to see in the navigation tree which sections contain missing answers.

**Comment by jochenklar** [comment]
This is a good idea, this is a bit like https://www.elster.de.

**Comment by jochenklar** [comment]
#346 is also about the navigation.

**Comment by m6121** [comment]
Potential Duplicate of #299 ?

**Comment by m6121** [comment]
Awesome that this has been implemented in #833 Many thanks for this contribution!
