### ISSUE TITLE
Progressbar: Questioncount with conditions

### ISSUE THREAD

**Issue by m6121** [rdmorganiser/rdmo#429]
In the old DFG catalog (https://github.com/rdmorganiser/rdmo-catalog/commit/8cc58d6c5a94369ed06ed1e1cb96694eba76f519) the first questionset asks if the research community has requirements while the second questionset is displayed only if the first was answered with 'yes' using a condition. Furthermore, the question inside the second questionset is not marked as "optional".

This results in the following situation: the progressbar counts this second question as missing if it is not filled although according to the answer in the first questionset (and, thus, also the condition), the question is skipped.

Is this a problem in the evaluation of the number of questions or is this a problem in the catalog which must also declare the questions inside some conditioned questionsets as optional?

**Comment by jochenklar** [comment]
Hi @m6121 , yes this is an open problem, see https://github.com/rdmorganiser/rdmo/issues/299 and https://github.com/rdmorganiser/rdmo/issues/322. In principle questionset which conditions are not met should be excluded from the progress bar. However this needs to be fast on the database since the request for the progress bar is done a lot.

**Comment by m6121** [comment]
Hi @jochenklar, thanks for the fast reply. I see. Unfortunately, our users were confused as they though they filled all information and the progressbar indicated this is not the case. This aimed at improving the answering workflow similar to #424

**Comment by m6121** [comment]
Awesome that this has been implemented in #679 respectively #833 Many thanks for this contribution!
