### ISSUE TITLE
Installing RDMO locally fails

### ISSUE THREAD

**Issue by vi-klaas** [rdmorganiser/rdmo#434]
Update: without upgrading to newest pip and setuptools, it works (Python 3.10).
Probably incompatible setuptools?

Tried to run rdmo locally with Python 3.8, 3.9., 3.10 and each time, installation fails with django-allauth:

(venv) klav@clt-mob-v-6095 rdmo-app % pip install --upgrade pip setuptools
Requirement already satisfied: pip in ./venv/lib/python3.8/site-packages (21.3.1)
Collecting pip
Using cached pip-22.0.4-py3-none-any.whl (2.1 MB)
Requirement already satisfied: setuptools in ./venv/lib/python3.8/site-packages (60.2.0)
Collecting setuptools
Using cached setuptools-61.0.0-py3-none-any.whl (1.1 MB)
Installing collected packages: setuptools, pip
Attempting uninstall: setuptools
Found existing installation: setuptools 60.2.0
Uninstalling setuptools-60.2.0:
Successfully uninstalled setuptools-60.2.0
Attempting uninstall: pip
Found existing installation: pip 21.3.1
Uninstalling pip-21.3.1:
Successfully uninstalled pip-21.3.1
Successfully installed pip-22.0.4 setuptools-61.0.0
(venv) klav@clt-mob-v-6095 rdmo-app % pip install rdmo
Collecting rdmo
Using cached rdmo-1.8.0-py3-none-any.whl (1.6 MB)
Collecting defusedcsv~=1.1.0
Using cached defusedcsv-1.1.0-py3-none-any.whl (7.5 kB)
Collecting jsonfield~=3.1.0
Using cached jsonfield-3.1.0-py3-none-any.whl (8.0 kB)
Collecting pytest-pythonpath~=0.7.3
Using cached pytest_pythonpath-0.7.4-py3-none-any.whl (3.7 kB)
Collecting django-compressor==2.4.1
Using cached django_compressor-2.4.1-py2.py3-none-any.whl (145 kB)
Collecting iso8601~=0.1.14
Using cached iso8601-0.1.16-py2.py3-none-any.whl (10 kB)
Collecting djangorestframework~=3.12.4
Using cached djangorestframework-3.12.4-py3-none-any.whl (957 kB)
Collecting django-rest-swagger~=2.2.0
Using cached django_rest_swagger-2.2.0-py2.py3-none-any.whl (495 kB)
Collecting django-cleanup~=5.2.0
Using cached django_cleanup-5.2.0-py2.py3-none-any.whl (9.9 kB)
Collecting drf-extensions~=0.7.0
Using cached drf_extensions-0.7.1-py2.py3-none-any.whl (21 kB)
Collecting django-mathfilters~=1.0.0
Using cached django_mathfilters-1.0.0-py3-none-any.whl (5.9 kB)
Collecting django-mptt~=0.12.0
Using cached django_mptt-0.12.0-py2.py3-none-any.whl (111 kB)
Collecting django-extensions~=3.1.3
Using cached django_extensions-3.1.5-py3-none-any.whl (224 kB)
Collecting django-allauth~=0.45.0
Using cached django-allauth-0.45.0.tar.gz (581 kB)
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "/private/var/folders/wx/lf0g2dz917lgrk434h0kjftw0000gp/T/pip-install-7z_ux9qg/django-allauth_3cf18744c03e45f295d2cad69096d3cc/setup.py", line 9, in
from setuptools import convert_path, find_packages, setup
ImportError: cannot import name 'convert_path' from 'setuptools' (/Users/klav/work/rdmo/rdmo-app/venv/lib/python3.8/site-packages/setuptools/init.py)
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(venv) klav@clt-mob-v-6095 rdmo-app %

**Comment by jochenklar** [comment]
Hi @klav-zhaw , thanks for the report. Fun thing: I cannot reproduce it with RDMO, but I have the same problem in an unreleated repository, also with django-allauth. I will investigate.

**Comment by jochenklar** [comment]
Hi again, I could reproduce it after creating a new virtual environement. @triole we need to pin `django-allauth` to `0.50.0`.

Workaround for now: `pip install setuptools==60.10.0` (before the installation of RDMO).

It seems setuptools 61 causes the problem.
