### ISSUE TITLE
Update requirements, in particular Django 4.0

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#442]
### Rationale / Begründung
Django 4.0 is out, we need to upgrade eventually. We should use this to review all other entries in `requirements.txt`.

**Comment by jochenklar** [comment]
Some code needs to be changed for django restframework 3.13: like here: https://github.com/django-daiquiri/daiquiri/pull/97/commits/3f3b56974423b6d2d6902ad243f50bb4a6e36854

**Comment by afuetterer** [comment]
I updated a few requirements in #664 already.

Once that is merged, the dependabot will start generating PRs again.

If you like, I can take over this issue in September.

**Comment by MyPyDavid** [comment]
are you gonna use this tool https://github.com/adamchainz/django-upgrade?  ;)

**Comment by afuetterer** [comment]
Yes, I will give it try. But thanks for pointing it out.

The author also points out https://django-codemod.readthedocs.io.
He says codemod is slower. But I think, this does need to be run once and not be part of the pre-commit hooks.

I will upgrade these with priority: django and drf.

Do you know, if all the other requirements are stil needed?
I pointed the issue with jsonfield out #692.
Also there is still this open issue #368.

Some of the dependencies have not received updates in a long time, e.g. https://github.com/chibisov/drf-extensions.

I will research the dependencies and report in the corresponding PR.

**Comment by afuetterer** [comment]
Could we also broaden some of the version constraints?

For example
`"Django~=3.2.20"` will only allow Django >= 3.2.20 and < 3.3

I would suggest using this form instead
`"Django~=3.2"`, allowing Django >= 3.2 and < 4.0

See: https://peps.python.org/pep-0440/#compatible-release

**Comment by afuetterer** [comment]
@MyPyDavid, you can assign this issue to me.

**Comment by afuetterer** [comment]
Refs:
- https://docs.djangoproject.com/en/4.2/howto/upgrade-version/
- https://docs.djangoproject.com/en/4.2/internals/deprecation/

**Comment by jochenklar** [comment]
Thanks for picking this up. I would not use a tool though. I did the migration once for a different project and it was pretty easy. I would just run the tests and fix the problems.

Are there particular problems with mptt and jsonfield and 4.2?

**Comment by afuetterer** [comment]
I will test the tool just to get to know it. But yes, the way you propose with fixing breaking tests makes sense.

No, there are no problems so far to my knowledge.

It was just an observation, that there is still an open issue regarding mptt. What to do with it?

**Comment by afuetterer** [comment]
```console
pip list --outdated                                                  
Package              Version Latest Type
-------------------- ------- ------ -----
coverage             6.5.0   7.3.0  wheel
Django               3.2.21  4.2.5  wheel
django-allauth       0.53.1  0.55.2 sdist
django-cleanup       6.0.0   8.0.0  wheel
django-filter        21.1    23.2   wheel
django-mptt          0.13.4  0.14.0 wheel
django-widget-tweaks 1.4.12  1.5.0  wheel
djangorestframework  3.12.4  3.14.0 wheel
Markdown             3.3.7   3.4.4  wheel
pypandoc             1.10    1.11   wheel
pytest-cov           4.0.0   4.1.0  wheel
```

- [ ] Django               3.2.21  4.2.5  wheel
- [ ] django-allauth       0.53.1  0.55.2 sdist
- [ ] django-cleanup       6.0.0   8.0.0  wheel
- [ ] django-filter        21.1    23.2   wheel
- [ ] django-mptt          0.13.4  0.14.0 wheel
- [ ] django-widget-tweaks 1.4.12  1.5.0  wheel
- [ ] djangorestframework  3.12.4  3.14.0 wheel
- [ ] Markdown             3.3.7   3.4.4  wheel
- [ ] pypandoc             1.10    1.11   wheel
- [ ] pytest-cov           4.0.0   4.1.0  wheel
