### ISSUE TITLE
Optionset with one option not selectable multiple times

### ISSUE THREAD

**Issue by triole** [rdmorganiser/rdmo#452]
Using an optionset with only one selectable option turns out to cause problems. After a fresh page load selecting the option works. But selecting and deselecting multiple times causes errors. In the browser's network console you can see that the web requests are messed up.

Here is what happens

![rdmoissue452](https://github.com/triole/testing/raw/master/img/rdmo_issue452.gif)

**Comment by jochenklar** [comment]
Might be related: https://github.com/rdmorganiser/rdmo/issues/324

**Comment by triole** [comment]
Fixing here: https://github.com/rdmorganiser/rdmo/pull/495
