### ISSUE TITLE
Importing project that uses unknown/missing catalogue uses random other catalogue

### ISSUE THREAD

**Issue by hardfalcon** [rdmorganiser/rdmo#455]
It appears that if you import a project which uses a catalogue that the importing RDMO instance doesn't know, another random catalogue is used instead without even showing a warning. This bug was found by @jmfrenzel.

**Comment by jochenklar** [comment]
It should be the first catalog that is used, I guess we should add a warning in the import screen.

**Comment by jmfrenzel** [comment]
> It should be the first catalog that is used, I guess we should add a warning in the import screen.
can confirm that it is the first catalog (first according to the catalog order in the instance). 

More importantly that first catalog is selected even when this catalog has the not available flag set.

**Comment by jochenklar** [comment]
> More importantly that first catalog is selected even when this catalog has the not available flag set.

Yeah, this is not optimal.

**Comment by hardfalcon** [comment]
Wouldn't it be better to outright reject the import if it uses an unknown catalog? My fear is that people assume some sort of "sane" behavior when the catalog used doesn't actually fit the questions answered, when IMO there is no "sane" behavior to handle this other than reject the import in the first place.

**Comment by jochenklar** [comment]
I beg to differ, catalogs can be chnged in RDMO and sometimes you want to import a project into an instance which does not have this catalog. I think we just need to make the behavior more visible.

**Comment by jochenklar** [comment]
Will be part of RDMO 2.2.0.
