### ISSUE TITLE
Add keycloak login via django-allauth

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#456]
## Rationale / Begründung

In order be to able to combine Shibboleth with other types of login ('social accounts') the rdmo instance should have the option to login via Keycloak.

## References / Verweise
Issue: [Shibboleth and other authentification systems #85](https://github.com/rdmorganiser/rdmo/issues/85)

## Status
Have deployed this feature on a test instance. Need to add the changes into a PR in `rdmo` , settings in the `rdmo-app` and parts in the documentation.

* `rdmo-app`: 
  *   added the settings to `sample.local.py`
  *  https://github.com/rdmorganiser/rdmo-app/pull/10
* `rdmo`: 
  * [added logo and snippet to provider_list.html 
  * https://github.com/rdmorganiser/rdmo/pull/481
* `docs`
  * [docs/configuration/authentication/allauth](https://github.com/rdmorganiser/rdmo-docs-en/blob/master/docs/configuration/authentication/allauth.md)
  * [docs/configuration/authentication/shibboleth](https://github.com/rdmorganiser/rdmo-docs-en/blob/master/docs/configuration/authentication/shibboleth.md)

**Comment by jochenklar** [comment]
Hi @MyPyDavid , thanks! If you have the time, feel free to add your setup to the docs, i.e. here: https://github.com/rdmorganiser/rdmo-docs-en/blob/master/docs/configuration/authentication/allauth.md

**Comment by jochenklar** [comment]
@MyPyDavid I think we can close this issue, right?

**Comment by MyPyDavid** [comment]
yes, the things still in todo are for the `docs` and the `rdmo-app`.
Ive posted an issue in the docs https://github.com/rdmorganiser/rdmo-docs-en/issues/17
