### ISSUE TITLE
For adding additional information to a catalog, allow question sets without questions

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#461]
### Rationale / Begründung

An editor of a catalog wants to give additional/summary information to the interviewee at the beginning or within a catalog. It should therefore be possible to add text information without the need to add a question. One way to achieve this would be to allow question sets without questions.

### Affected 

Users, Managers

### Minimal functionality

Question sets without questions show the help text and the user can click on "proceed" to move on to the next section / question set.

**Comment by jochenklar** [comment]
Ones thing I always thought about was to rename the QuestionSets to Pages, this would distinguish them in respect to the nested Questionsets.

**Comment by jochenklar** [comment]
I think this is now already possible (although there was a bug) and @Sabine-Schoenau is using it.

**Comment by Sabine-Schoenau** [comment]
Aber erst mit der neuesten Version, richtig?

 

Von: Jochen Klar ***@***.***> 
Gesendet: Donnerstag, 4. August 2022 16:19
An: rdmorganiser/rdmo ***@***.***>
Cc: Schönau, Sabine ***@***.***>; Mention ***@***.***>
Betreff: Re: [rdmorganiser/rdmo] For adding additional information to a catalog, allow question sets without questions (Issue #461)

 

I think this is now already possible (although there was a bug) and @Sabine-Schoenau <https://github.com/Sabine-Schoenau>  is using it.

**Comment by MyPyDavid** [comment]
thanks, we've tested it in a 1.7.0 version and it works. 

We would also like to rename the QuestionSets to Pages, i'll make a new issue for that and close this one.
