### ISSUE TITLE
Add import/export of a catalog and its related items (optionsets, conditions, tasks etc.)

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#464]
### Rationale / Begründung

An editor wants to reuse catalogs from different sources or copy catalogs from a test-environment to the production environment.

When exporting a catalog, the related elements (optionsets, conditions, tasks etc.) are not exported in one action. The user needs to select those items via different menus and export processes. 
For easier import/export of catalogs and to make the reuse of catalogs easier, these elements should be exported in the same action.
Via catalog export all related items should be exported as well, e.g. in a combined xml-file or a .zip-archive with multiple files.
The import of a catalog should work accordingly, which means one xml-file ~~or
multiple files or a combined .zip archive~~ can be uploaded in one action.

### Affected 

Managers, Admins

### Minimal functionality

* by choosing catalog export the catalog and all related items are downloaded in one action
  * the files are combined in one .xml file or a .zip file
* import can handle a catalog and its related element from one .xml file

**Comment by jochenklar** [comment]
I would not include zip files here. All elements can be located in one xml file without problems. Right now you can already manually create xml files which can be used to import options, attributes, and catalogs at once, btw.

**Comment by MyPyDavid** [comment]
Could this export of a catalog and its related elements into a single .xml file be included in the next 2.2.0 release? The preparation seems to be there already

**Comment by jochenklar** [comment]
Even better, it should already work in the current release (actually all RDMO >= 2.0. One quirk is that not the full tree of attributes is exported. I am not sure what is expected here.

**Comment by MyPyDavid** [comment]
Thanks! think it's fine like this.
Can be found under `/management/catalogs` > Export catalog (button) > XML (full)
