### ISSUE TITLE
show an overview of the import errors/warnings at top of page during catalog import

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#465]
### Rationale / Begründung

An editor needs a short overview of errors occurring during the catalog import.

At the start of a catalog import all errors/warnings occurring are mentioned next to each imported question. It would be easier if a list of all errors is presented at the top of the import table as well.

### Affected 

Managers 

### Minimal functionality

* add an additional paragraph at the top of the management/upload/ section "Warnings"/"Meldungen" and collect there a list or table with all the error messages

### Nice-to-have functionality

What sort of related functionality would you like to see in addition?

### References / Verweise
* https://github.com/rdmorganiser/rdmo/issues/272
* https://github.com/rdmorganiser/rdmo/issues/465

**Comment by jochenklar** [comment]
@MyPyDavid is the error handling in the import in `2.0.0` sufficient?

**Comment by MyPyDavid** [comment]
we will look at this next week

**Comment by MyPyDavid** [comment]
I still want to check this in combination with https://github.com/rdmorganiser/rdmo/issues/465 but the minimal functionality is there in [2.0.0](https://github.com/rdmorganiser/rdmo/releases/tag/2.0.0)

**Comment by jochenklar** [comment]
Will be part of RDMO 2.2.0.
