### ISSUE TITLE
allow base uri and key to be defined during catalog import

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#466]
### Rationale / Begründung

An editor should be able to change Base-URI and key of the catalog during import.

### Affected 

Managers

### Minimal functionality

* at the top of management/upload/ section two single-line text fields are shown. One for "Base-URI" (with value=Base URI defined in the catalog.xml) and one "Key" (with value=key defined in catalog.xml). The user is able to change URI and Key.
* The import checks if base-URI and key are already in the database and shows an Info text "Base-URI and Key exist"

**Comment by jochenklar** [comment]
Addressed in [RDMO 2.0.0](https://github.com/rdmorganiser/rdmo/releases/tag/2.0.0).
