### ISSUE TITLE
allow available setting to be defined during catalog import

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#467]
### Rationale / Begründung

When importing a new catalog, an editor would like to have the option "available" set to False. 

As an editor it might be necessary to edit a catalog after the import, this catalog should not be visible to users.

### Affected 

Managers

### Minimal functionality

* let the available setting be definable at import or have it default to False.

### References / Verweise

* https://github.com/rdmorganiser/rdmo/issues/466

**Comment by jochenklar** [comment]
This could be done with a setting, like `QUESTIONS_DEFAULT_CATALOG_AVAILABILITY`. Same should be added for views and tasks.

**Comment by jochenklar** [comment]
Addressed in [RDMO 2.0.0](https://github.com/rdmorganiser/rdmo/releases/tag/2.0.0).
