### ISSUE TITLE
more detailed update message during catalog import

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#468]
### Rationale / Begründung

An editor wants to check how the new and old version of the catalog differ.

When importing a new version of a catalog, for every existing entry a message "This element will be updated." is shown. It would be helpful if exact changes are listed during the import as well.

### Affected 

Managers

### Minimal functionality

* a more detailed information is given what is changed during the update (e.g. similar to git diff)

### References / Verweise

* Nearly similar to https://github.com/rdmorganiser/rdmo/issues/272
* https://github.com/rdmorganiser/rdmo/issues/653

**Comment by jochenklar** [comment]
Will be part of RDMO 2.2.0.
