### ISSUE TITLE
Admin interface improvement

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#47]
As admin, a user wants a more convenient admin interface including an improved search functionality.

**Comment by Zack-83** [comment]
In the admin view, the highest divisions of a catalogue ("sections") are called in German "Unterabschnitt" instead of "Abschnitte"

![grafik](https://user-images.githubusercontent.com/37865804/38819497-dba8d926-419b-11e8-8cdf-18cb1db8f5b7.png)

**Comment by jochenklar** [comment]
The improvements were done as part of the "refactoring of 2018".
The bug was fixed in 7a8b9b98b6afd7efc5025192c7721df971d8970e.

**Comment by Zack-83** [comment]
Das ist Telepathie!

LG


Von:    "Jochen Klar" <notifications@github.com>
An:     "rdmorganiser/rdmo" <rdmo@noreply.github.com>
Kopie:  "Zack-83" <giacomo.lanza@ptb.de>, "Comment" 
<comment@noreply.github.com>
Datum:  18.10.2018 12:30
Betreff:        Re: [rdmorganiser/rdmo] Admin interface improvement (#47)



Closed #47.
?
