### ISSUE TITLE
Clarity in complex client versions

### ISSUE THREAD

**Issue by frankRuehle** [rdmorganiser/rdmo#473]
Improve clarity in the client version with more than 20 catalogs. In RDMO, many different institutions (= clients) can be managed together in one RDMO installation. With many different question catalogs per client, a clear assignment of client and question catalogs would be useful. 
[This issue is from 7th RDMO community meeting on March 2, 2022]

**Comment by jochenklar** [comment]
We can only address this when implementing a new front-end: https://github.com/rdmorganiser/rdmo/issues/518

**Comment by jochenklar** [comment]
In the new interface, catalogs (and everything else) can now be filtered by site and uri prefix.

**Comment by MyPyDavid** [comment]
Can be closed by [2.0.0](https://github.com/rdmorganiser/rdmo/releases/tag/2.0.0)?
