### ISSUE TITLE
Tooltips do not work

### ISSUE THREAD

**Issue by leucoryx** [rdmorganiser/rdmo#483]
Expected behavior:
Tooltip in the helptext written as [text]{tooltip} should highlight "text" and show "tooltip" in an extra window.

Result:
The "text" is missing / not show in the questionaire.

Attempts:
[text](tooltip), (text){tooltip) failed

**Comment by jochenklar** [comment]
Hi @leucoryx , can you say in which help text this occurs?

**Comment by leucoryx** [comment]
In the help texts of the questions. "Hilfe (Deutsch)" and "Hilfe (Englisch)"
