### ISSUE TITLE
show progress values of subprojects in parent project page (overview of status of multiple projects)

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#488]
### Rationale / Begründung

In order to have a better overview on the status of multiple subprojects, the value for the progress property could be shown in the parent project (overview) page.

A manager of multiple projects needs to keep an overview of the status of DMPs in the subprojects.

### Affected 

Users

### Minimal functionality

* show the project progress (ratio or values/total) in the Project hierarchy list of subprojects

### References / Verweise

* #487
* #429

**Comment by jochenklar** [comment]
The progress is quiet complicated to compute (fast), so this task could be harder than expected.
