### ISSUE TITLE
(Account-)Routes don't use BASE_URL

### ISSUE THREAD

**Issue by vi-klaas** [rdmorganiser/rdmo#493]
I dockerized RDMO and want to use RDMO with https://mydomain.ch/rdmo

I configured NGINX with location /rdmo and added a rewrite rule 

rewrite ^/rdmo(/?)(.*)$ /$2  break;

since adding BASE_URL = '/rdmo' leads to the error page stating that /rdmo is unknown route:
http://mydomain.ch:443/rdmo/ -> not sure if this is a config error in nginx or if I need to add something to local.py concerning https?

With the rewrite route, I get the home page. When I try to login, it leads to

https://mydomain.ch/account/login/

which is missing the /rdmo between domain and account. Following the login-link in the menu in the top left leads to the correct URL. Switching the language is also leading to the wrong URL. As well as the /admin.

I noticed a function sanitze_url that you are using in the settings/__init__.py Not sure if it is doing it's job correctly and if you are sanitizing all URLs of allauth and for the language that are needed

**Comment by klav-zhaw** [comment]
Actually, testing again without the rewrite rule, I noticed that RDMO receives a "weird" URL:
http://mydomain.ch:443/rdmo/ 
-> not sure if this is a config error in nginx or if I need to add something to local.py concerning https? I added already 

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

Not sure if this is the right thing to do

**Comment by klav-zhaw** [comment]
And I see this:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/81251575/167894293-d88760d2-47fe-418a-9825-af272f63e7f8.png">

**Comment by klav-zhaw** [comment]
Actually, my setup is one docker-compose file to run NGINX and one docker-compose file where I have the Django-RDMO-App and postgres, and to do that I followed some tutorials other than the documentation and without the /rdmo it is working even without the systemd service file.

BASE_URL = "/rdmo"

Can't we just redefine the urlpatterns that is defined in rdmo-app/config/urls.py
path('', include('rdmo.core.urls')), -> path('', include('rdmo.core.urls'))

and also all the other url_patterns:
path(sanitize_url(BASE_URL + 'accounts/'), include('rdmo.accounts.urls'))

**Comment by johlton** [comment]
Just ran into this problem with RDMO in a sub directory and the `--env SCRIPT_NAME=</SUB_DIRECTORY>` within `ExecStart` directive in the gunicorn systemd unit made the difference. So yes, please add this to documentation! :)
