### ISSUE TITLE
using allauth AUTHENTICATION_BACKENDS did not exist to append

### ISSUE THREAD

**Issue by klav-zhaw** [rdmorganiser/rdmo#494]
Instead of the append command, I had to use this:

AUTHENTICATION_BACKENDS = ['allauth.account.auth_backends.AuthenticationBackend',]

**Comment by jochenklar** [comment]
I guess you skipped importing `AUTHENTICATION_BACKENDS`?

```
from rdmo.core.settings import INSTALLED_APPS, AUTHENTICATION_BACKENDS

...

AUTHENTICATION_BACKENDS.append('allauth.account.auth_backends.AuthenticationBackend')
```

If you redefine the setting the regular login, e.g. for the user created with `./manage.py createsuperuser` will not work anymore, I guess.

**Comment by klav-zhaw** [comment]
Right, I missed to uncomment the import statement. I could still log in into the admin-interface with the createsuperuser-User.
