### ISSUE TITLE
response time of management pages correlates with the number of attributes 

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#500]
### Rationale / Begründung

An editor and an admin of a test instance were faced with a database containing nearly 2000 attributes and a sub-optimal response time of loading modals forms in the management area.
After deleting half of the attributes (duplicates, old versions, etc..) the response time was more or less halved. 

When some parts in the [`catalog.js`](https://github.com/rdmorganiser/rdmo/blob/dbdcc1f2eb6e033e377898a8bf198282f82813c1/rdmo/questions/static/questions/js/catalogs.js#L201) were blocked, the modal forms also appeared instantly.

Is it possible to test the performance of the AngularJS parts independently of browsing the pages?  

Could a performance check for the management pages with a large number of items (attributes, optionsets or conditions) be taken into account in a future 2.0 release of the front-end?

### Affected 

Managers, Admins

### References / Verweise

* https://github.com/rdmorganiser/rdmo/blob/dbdcc1f2eb6e033e377898a8bf198282f82813c1/rdmo/questions/static/questions/js/catalogs.js#L193

**Comment by jochenklar** [comment]
This was addressed in [RDMO 2.0.0](https://github.com/rdmorganiser/rdmo/releases/tag/2.0.0).
