### ISSUE TITLE
Attribute URI in the JSON API

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo#506]
### Rationale / Begründung

At present the JSON API labels the fields only with anonym numbers.
For higher clearity, I suggest including also the RDMO URI of each attribute in the JSON API output, similarly as in the XML export.

### Affected 

Who is affected by the change: Managers, Admins, creators of catalogues and views (for troubleshooting)

![image](https://user-images.githubusercontent.com/37865804/176141028-386d9886-38da-4ab8-b2b8-a45e0d793612.png)

![image](https://user-images.githubusercontent.com/37865804/176141917-68258c9a-eba0-4770-94e7-832ad6f17958.png)

**Comment by jochenklar** [comment]
@Zack-83 of course! This is also pretty easy to implement.
