### ISSUE TITLE
Tippfehler im Englischen

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo#508]
### Description / Beschreibung

Hallo,
die folgenden Textbausteine sind falsch geschrieben und sollten (im Code und anschließend in den .PO-Dateien) korrigiert werden:

Email --> e-mail (groß oder klein)
and it's descendants --> and its descendants
and it's options --> and its options
and it's sections --> and its sections
and it's questions --> and its questions
and it's question sets --> and its question sets

**Comment by jochenklar** [comment]
done.
