### ISSUE TITLE
Do not change tab when answering questions for additional datasets

### ISSUE THREAD

**Issue by Leifheitxxl** [rdmorganiser/rdmo#510]
### Rationale / Begründung
Currently, after you add an additional data set, answer questions and hit "save and proceed", the tab with the first dataset is activated again. This is not very intuitive.

### Affected 

Users

### Minimal functionality

The tab of the last added / current dataset should stay activated.

### Nice-to-have functionality

---

### References / Verweise

---

**Comment by jochenklar** [comment]
Hi @Leifheitxxl , I think this is already fixed, but I cannot find the corresponding issue myself. It ended up in release https://github.com/rdmorganiser/rdmo/releases/tag/1.7.0 though.

When clicking "Save and proceed" RDMO should switch to the next questionset, but keep the same "Dataset" tab as before.

Maybe you run an older version of RDMO or you have `PROJECT_QUESTIONS_CYCLE_SETS` set to `True` in the settings.

**Comment by Leifheitxxl** [comment]
Hi! Many thanks for the quick reply. I was not aware that the RDMO instance my institution is running is quite outdated.
