### ISSUE TITLE
Sorting causes problems with import

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#523]
### Description / Beschreibung

When using different `uri_prefix`es for, e.g. a domain import, the sorting by `uri` destroys the order in the file, and parent Attributes are imported *after* their children (with a different `uri_prefix` earlier in the alphabet). This is the problematic line:

https://github.com/rdmorganiser/rdmo/blob/master/rdmo/core/xml.py#L52

### Expected behaviour / Erwartetes Verhalten

I am not sure if we could get rid of the sorting, we could also sort by `path` (which would give the field some meaning in the xml again). Ideas? @triole @MyPyDavid

**Comment by MyPyDavid** [comment]
could you not find the different `uri_prefixes`  _first_ and loop over them to keep them separate?  
Don't know if it applies here, would need to reproduce it to better see it..

**Comment by jochenklar** [comment]
Well to match the parents, the `path` is the important value. With the `uri_prefixes` it could also fail in the other direction, if the child is from `rdmorganiser.github.io` and the parent from somewhere else.
