### ISSUE TITLE
[API] Connect with 3rd party app

### ISSUE THREAD

**Issue by Commifreak** [rdmorganiser/rdmo#539]
Hi,

I dont found any best practice in the docs, so Iam asking here. If this is not ok, please lead me to the right direction...

I have a PHP app with its own user management. And we have RDMO. Both should exchange data. I want to use the RDMO API for that. So far so good.

RDMO has LDAP enabled. The PHP App as well.

I want to link data with the users account, which is sending from the PHP app. But the user does not yet exist in RDMO. Not a problem, he could easily sign in one time. But for API comms, I need his Token. And this token is only  requestable via Django -> Tokens.

There is no way (currently?) to get a Token via RDMO API.

My question is:

* Is there a way to retrive a user token in his context? (I also would have a super user which could make API calls, but this doesnt helps currently)
* Has Django User admin its own API I could use?
* Is the OAuth2 option (https://rdmo.readthedocs.io/en/latest/configuration/authentication/allauth.html) the better way here?

Any advice is appreciated :)

Thanks in advance!

**EDIT**: As I see, I HAVE to go with Django Admin, because RDMO requires a Token to authenticate (`In order to access any data entered into RDMO through the programmable API, a user needs to have a token associated with him.`) . 

If thats true, the RDMO API should have options to generate a users token and give it back. Its also missing from `/api/v1/accounts/users/` responses.

A user is currently not able to create a token itself.

**Comment by Commifreak** [comment]
I changed behavior: I use one user to make API comms and create memberships in with it, by send the correct user id now. To retrieve a non exitent user, I let him login one time and search it via email via API to get his userid.

**Comment by jochenklar** [comment]
Hi @Commifreak , you already closed, but let me leave a comment: This would be actually a nice feature, but would need RDMO to fully support OAUTH to let users allow other services to access  RDMO content. We use OAUTH only for authentication with ORCID, GitHub, etc.

You correctly saw that the API token is not for regular users, but more for dedicated users to be used in scripts. There is also the `api` group in RDMO for this purpose.
