### ISSUE TITLE
Add priority labels to Issues

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#542]
The Issues were ranked in priority in the Community Meeting Survey. 
* [x] the rankings should be categorized (low, middle, high)
 *  https://github.com/rdmorganiser/rdmo/labels/priority%3A%20low
 * https://github.com/rdmorganiser/rdmo/labels/priority%3A%20medium
 * https://github.com/rdmorganiser/rdmo/labels/priority%3A%20high
* [x] each Issue should be labeled with its priority

**Comment by jwindeck** [comment]
priority according to community voting: https://www.forschungsdaten.org/index.php/Achtes_Community-Treffen#Im_Nachgang:_Ergebnisse_der_Auswertung_der_Frageb.C3.B6gen

low < mean value
middle < 3.5
high >= 3.5
