### ISSUE TITLE
[Invitation/LDAP] After login, invitation is not being handled. A second URL call is required

### ISSUE THREAD

**Issue by Commifreak** [rdmorganiser/rdmo#544]
### Description / Beschreibung

**We have enabled LDAP, maybe this is important!**

I invite a users (which are **not** currently in RDMO) via invitation form. The user recieves the mail with its `projects/join/xxxx` link. All good.
The user hits the link and gets the login. Since we have LDAP enabled, the user simply enter its credentials and can log in.

Now comes the issue: RDMO redirects the user NOT to the invitation but to the dashboard. The user was just created on-the-fly (because of ldap). A second click on the link is now required to really join the project.

### Expected behaviour / Erwartetes Verhalten

* User clicks on link.
* User logs in
* User is added as project member

### Steps to reproduce / Schritte zum Reproduzieren

See above

### References / Verweise

*

**Comment by jochenklar** [comment]
Hi @Commifreak , by dashboard ou mean `/projects/` right? So the projects overview table.

**Comment by Commifreak** [comment]
Excatly.

**Comment by Commifreak** [comment]
TBH, I dont know if its a pure redirect issue by the login or something with the ldap-on-the-fly-user-creation

**Comment by Commifreak** [comment]
Could you already took a closer look into this? Or is this a bigger issue?

**Comment by jochenklar** [comment]
Hi @Commifreak , good that you reminded me! However, I activated my old LDAP test setup and it works here as excpected. Maybe something is different in your setup. Here are my steps:

1. I am logged in as `admin` and have a project `Test`.
2. on `/projects/1/memberships/create/` I create a (non-silent) invite for `user@example.com` as `Author`.
3. I open the invite url `/projects/join/a4b22fc560ee9334c555/` in a different browser.
4. I get redirected to `/account/login/?next=/projects/join/a4b22fc560ee9334c555/`
5. I log in as `user` (who is in the LDAP but not in RDMO, yet).
6. I get redirected to `/projects/1/` and am now `Author` of it.

Can you reproduce this? Where does your system deviate?

**Comment by jochenklar** [comment]
I think the crucial part is the `?next=/projects/join/a4b22fc560ee9334c555/` in the login link. if that gets lost, you will be redireted to `/projects/.

**Comment by Commifreak** [comment]
Hmm. Okay, I just tested it again:

- The user is NON existent in the system, ldap enabled.
- I click the link à la `https://rdmo.host.tld/projects/join/0a1b2c3d/`
- The browser adjusts the link to `https://rdmo.host.tld/account/login/?next=/projects/join/0a1b2c3d/`
- I login, using my ldap credentials:
  - Response Header from rdmo: 
Code: 302
`Location: /` <-- The invitation is lost here!

- The browser calls `/` -> 302 -> `/projects/`.
- The user is logged in and sees the empty projects list

The `/account/login/` POST request does NOT respons with the correct `Location` header in my test case :(
Testing it with existing account does not work either. But the `Referer` Request header is set correctly with the ?next-part.

rdmo works behind a reverse proxy, but I dont cut any headers or something:

```
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {

	    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    ssl_certificate /etc/nginx/ssl/rdmo.cert;
    ssl_certificate_key /etc/nginx/ssl/rdmo.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    # curl https://ssl-config.mozilla.org/ffdhe2048.txt > /path/to/dhparam
    ssl_dhparam /etc/nginx/ssl/ffdhe2048.txt;

    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;

	server_name rdmo.host.tld;

	location / {
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        	proxy_set_header X-Forwarded-Proto $scheme;
        	proxy_set_header Host $http_host;
	        proxy_pass http://unix:/home/rdmo/rdmo.sock;
	}

    	location /static/ {
        	alias /home/rdmo/rdmo-app/static_root/;
    	}

}
```

What now to check?

**Comment by jochenklar** [comment]
Ah, my mistake, if `allauth` is not in `INSTALLED_APPS`, the default login form is used, and the next hidden field is not rendered into the form. (This is how it actuall works, the `next` parameter is picked up by the GET view of the login form and then provided to the template as `redirect_field_value`, see: https://github.com/rdmorganiser/rdmo/blob/master/rdmo/accounts/templates/account/login_form.html#L14). I will have a look how to fix this.

**Comment by jochenklar** [comment]
Should be fixed in 1089d957f7453a7f20886e8c3b221cc7157866cf. The `allauth` uses `redirect_field_name` and `redirect_field_value`, while plain Django uses only `next` and stores it's value in the `{{ next }}` variable.

**Comment by Commifreak** [comment]
Looks promising. Ill give it a shot tomorrow by patching by hand.

**Comment by Commifreak** [comment]
Yep, its working properly now :)
