### ISSUE TITLE
The URI prefix dropdown in /domain stays empty

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#552]
### Description / Beschreibung

After our update from `1.7.0` to `1.9.0` the URI prefix dropdown in `/domain` under "Filter attributes" remains empty. 

### Expected behaviour / Erwartetes Verhalten

The dropdown has a list of selectable uri prefixes

### Steps to reproduce / Schritte zum Reproduzieren

1. Go to `/domain`
2. Click on "All URI prefixes" dropdown
3. See only an empty " " option

### References / Verweise
HTML snippet:
```html
<div class="form-group">
        <select class="form-control ng-pristine ng-valid ng-empty ng-touched" ng-model="service.uri_prefix">
            <option value="">All URI prefixes</option>
            <!-- ngRepeat: uri_prefix in service.uri_prefixes --><option ng-repeat="uri_prefix in service.uri_prefixes" value="" class="ng-binding ng-scope">
                
            </option><!-- end ngRepeat: uri_prefix in service.uri_prefixes -->
        </select>
    </div>
```

Seems like `service.uri_prefixes` stays empty or is filled with only one empty value.
https://github.com/rdmorganiser/rdmo/blob/3e38767ec8b62a6ccfd72fd779f7d7739c792dce/rdmo/domain/static/domain/js/domain.js#L33

**Comment by jochenklar** [comment]
This was broken for a long time, btw. at least in 1.8.0.

**Comment by MyPyDavid** [comment]
somehow missing in `1.9.1` need new pr for `1.9.2`

**Comment by MyPyDavid** [comment]
closed in https://github.com/rdmorganiser/rdmo/releases/tag/1.9.2
