### ISSUE TITLE
Users with same email can not be invited

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#561]
### Description / Beschreibung

Surprisingly, email addresses in RDMO don't have to be unique. I you invite an existin user to a project via email with a non unique mail the managers `.get()` function raises a `MultipleObjectsReturned`.

### Expected behaviour / Erwartetes Verhalten

(a) emails should unique in the first place or
(b) both users should be invited

Probably (b) is easier to implement.

**Comment by jochenklar** [comment]
@MyPyDavid @m6121 I solved the riddle, users with the same email cannot sign up (using allauth), but they can created in the admin interface.

**Comment by m6121** [comment]
Ah, that's interesting. Should we add a check in the admin interface to avoid duplicate mails from here?

**Comment by jochenklar** [comment]
I think its fine, maybe there is some reason for this.
