### ISSUE TITLE
Handling of project invitation links across multi sites

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#576]
### Rationale / Begründung

For a multi-site deployment, the invitation link in the e-mail doesn't work correctly when a user (the inviter from site A) invites a user (the invitee, member of site B) who is a user from a different site.
The link in the email should be adjusted for the invitee when there is already a user present, in RDMO with the same email address, as member of an other site.

### Affected 

Users

### Minimal functionality

* `user1` from `site A` sends an invite for a project to `user2` from `site B`
* `user2 `receives an invite link for a project on `site B` (instead of site A)

### References / Verweise

* [/projects/email/project_invite_message.txt](https://github.com/rdmorganiser/rdmo/blob/ef6e1f84e9e74212cfcbce5d75b12831a09d2b6f/rdmo/projects/templates/projects/email/project_invite_message.txt)
* https://github.com/rdmorganiser/rdmo/blob/ef6e1f84e9e74212cfcbce5d75b12831a09d2b6f/rdmo/projects/views/membership.py#L52

**Comment by jochenklar** [comment]
Good catch! To make it work as intended we need to get the site of the new user from `invite.user` and not from `request`. If a user has more than one site (as `member`) we should use the first. And use the one from `request` as a fallback.

**Comment by MyPyDavid** [comment]
I have something like this now for a function in `utils.py` for example;
```py
def invite_email_internal_site_redirection(request, invite) -> str:
    
    project_invite_path = reverse('project_join', args=[invite.token])
    
    # check if there are multiple sites and if the user is a member of any of them
    if Site.objects.count() == 1 or not invite.user.role.member.exists():
        return request.build_absolute_uri(project_invite_path)
    
    # prefer current site if user is a member of it
    current_site = Site.objects.get_current()
    if invite.user.role.member.filter(domain=current_site.domain).exists():
        return request.build_absolute_uri(project_invite_path)
    
    # else take first site
    invited_user_member_domain = invite.user.role.member.first().domain
    invite_uri = request.build_absolute_uri('http://' + invited_user_member_domain + project_invite_path)
    return invite_uri
```
but the tests have to be combined with the test fixtures for the multisite from https://github.com/rdmorganiser/rdmo/pull/565

**Comment by jochenklar** [comment]
* I would call it `get_invite_email_uri`. Redirection is something else.
* You can use `settings.MULTI_SITE` to check if you are in a multi site environment, the templates do that all the time.
* And maybe turn it upside down, with `return request.build_absolute_uri(project_invite_path)` at the end, and another return *if* you actually find another uri to return.

**Comment by MyPyDavid** [comment]
Thank you! 
Do you mean it like this? I've also kept the `request` object now out of the function, so that the `build_absolute_uri` is done in the `FormView` again.
```py
def get_invite_email_invite_path(invite) -> str:
    
    project_invite_path = reverse('project_join', args=[invite.token])
    # check if there are multiple sites and if the user is a member of any of them    
    if settings.MULTISITE or invite.user.role.member.exists():
        # do nothing if user is a member of the current site
        current_site = Site.objects.get_current()
        if not invite.user.role.member.filter(domain=current_site.domain).exists():
            # else take first site
            invited_user_member_domain = invite.user.role.member.first().domain
            project_invite_path = 'http://' + invited_user_member_domain + project_invite_path
    return project_invite_path
```

**Comment by MyPyDavid** [comment]
closed in https://github.com/rdmorganiser/rdmo/releases/tag/1.9.1
