### ISSUE TITLE
Project invitations are always expired

### ISSUE THREAD

**Issue by johlton** [rdmorganiser/rdmo#580]
### Description / Beschreibung

Invitations don't work for us in RDMO 1.9:

1. Person A adds Person B to an existing project.
2. Person A sees Person B appearing correctly in the "Invites" panel of the project
3. Person B gets an email with the invitation link and clicks it
4. Person B sees RDMO complaining, that the invitation has expired
5. Person A sees that Person B is removed from the "Invites" panel of the project

We already checked the obvious:

* Timezone in `config/settings/local.py` is "Europe/Berlin"
* Datetimes are corresponding:
  * Server: 2023/02/03 - 14:31:08 CET
  * Mail: 2023/02/03 - 14:31:34 CET

We would assume this is not a Daylight Saving Time problem.
It's even more puzzling cause I see [Pull Request 579](https://github.com/rdmorganiser/rdmo/pull/579) which suggests that this should work perfectly.

### Expected behaviour / Erwartetes Verhalten

The user is provisioned for the project.

### Steps to reproduce / Schritte zum Reproduzieren

1. Go to 'Project'
2. Click on 'Add member'
3. Enter a RDMO User ID
4. Choose some role
5. Click "Invite member"
6. See chosen RDMO User ID in the "Invites" panel
7. RDMO User clicks the link in the email

### References / Verweise

* There was another person in RDMO Slack (Support-Channel) with exact the same problem (19.01.2023)

**Comment by MyPyDavid** [comment]
Hi @johlton , I haven't seen any bug like this yet in our deployment.
The invite expiration is checked here:
https://github.com/rdmorganiser/rdmo/blob/dd0a23244adfa9d371463e63e71f68cea35e2eef/rdmo/projects/models/invite.py#L63

Did you set a value for `PROJECT_INVITE_TIMEOUT` in your settings? If so, is the value an appropriate amount of seconds?

**Comment by jochenklar** [comment]
Maybe somehow `settings.PROJECT_INVITE_TIMEOUT` is a string in your case? Or `0`?

**Comment by johlton** [comment]
Thanks for getting back! I left `settings.PROJECT_INVITE_TIMEOUT` at `False` in our `local.py`:
````
PROJECT_SEND_INVITE = True
PROJECT_INVITE_TIMEOUT = False
````

As stated in the [docs](https://rdmo.readthedocs.io/en/latest/configuration/email.html) this should work. But when I see the code, of course it's not gonna work because `False` is not `None`, right?

**Comment by johlton** [comment]
OK, I changed it to `None` and now it works. It also works if I use a real value like 259200 (3 days). So, I was just a victim of  documentation ;) Thanks for pointing that out, I could've had a look in the code myself, sorry for that.

**Comment by jochenklar** [comment]
Mhm, I think we should change that to `if PROJECT_SEND_INVITE`, because a value of 0 makes no sense anyway. Fun fact `int(False)` is `0` in Python (just tested).

**Comment by MyPyDavid** [comment]
that is also an unfortunate mismatch between the docs (`False`) and the code (`None`) ...
https://github.com/rdmorganiser/rdmo/blob/dd0a23244adfa9d371463e63e71f68cea35e2eef/rdmo/core/settings.py#L283

FYI, because `False.__int__()` is defined as `0`  it returns that.. ;)
and `False.__float__()` returns `0.0`
https://docs.python.org/3/library/functions.html#int

`bool` is even a subclass of `int`!
https://docs.python.org/3/library/functions.html#bool

**Comment by MyPyDavid** [comment]
a reminder, do you want to take this in `1.9.2` @jochenklar ?
