### ISSUE TITLE
Longer text fields for additional input in option sets

### ISSUE THREAD

**Issue by chsinn** [rdmorganiser/rdmo#594]
### Rationale / Begründung

For additional input, a short text field is not always enough. Sometimes a complete sentence is required as input. For this, a larger text field or even a textarea would be helpful and look more attractive.
![issue1](https://user-images.githubusercontent.com/113421464/223761779-c128ffbb-2060-4c0c-b6c2-ae25aedc0d12.png)

### Minimal functionality

The text field should appear in a new line under the option.

### References / Verweise

* rdmo v1.92

**Comment by MyPyDavid** [comment]
I've had some hints from @jochenklar about this issue:

Another `additional_input`  text block eg.  `additional_text_area` could be added with  `ng-show` and `type="text_area"` in the template
* https://github.com/rdmorganiser/rdmo/blob/813df5e0b01a24183a6d989e53d31685f492d6dc/rdmo/projects/templates/projects/project_questions_form_group_radio.html#L32

**Comment by jochenklar** [comment]
Tiny correction its `<input type="text">` and `<textarea>`, HTML is weird sometimes.
