### ISSUE TITLE
Progress bar refers to the first data set only

### ISSUE THREAD

**Issue by chsinn** [rdmorganiser/rdmo#596]
### Description / Beschreibung

The progress bar refers to the first dataset only. If more datasets are added, then the number of questions in the display does not increase. 

![pbar2](https://user-images.githubusercontent.com/113421464/224041650-37b1bff0-6b7d-4b0c-beed-52eb24524a45.png)

### Expected behaviour / Erwartetes Verhalten

The number of questions asked in relation to a dataset must be counted in relation to the number of datasets.

### Steps to reproduce / Schritte zum Reproduzieren

1. Create a project with a catalog that has questions related to datasets, e.g. the RDMO catalog.
2. Answer at least a quarter of the questions, then the number is displayed in the progress bar.
3. Create a new dataset when answering the questions
4. Watch the number of questions in the progress bar

### References / Verweise

*  rdmo 1.92

**Comment by jochenklar** [comment]
Yes, it just checkes if there is a `Value` for evert attribute used in the catalog. This is related to https://github.com/rdmorganiser/rdmo/issues/429 and https://github.com/rdmorganiser/rdmo/issues/299 and should be resolved together.
