### ISSUE TITLE
Warning message "Multiple answers exist in the database ..." displayed for checkboxes

### ISSUE THREAD

**Issue by chsinn** [rdmorganiser/rdmo#597]
### Description / Beschreibung

If more than one checkbox is set in a question with checkboxes as an answer option, the message
"Warning: Multiple answers exist in the database. This can happen due some technical problem in the past. You can remove unwanted answers using the "Remove item" field (). Please contact support if the problem persists."
always appears.

### Expected behaviour / Erwartetes Verhalten

The warning message should no longer be displayed.
ALternatively: A message should appear that the checkbox "is collection" must be set. Ideally this is done by itself as soon as checkboxes are selected instead of radio buttons.

### Steps to reproduce / Schritte zum Reproduzieren

1. Take a question with an option set behind it and set the type of widget to checkboxes.
2. In the properties of the questions, the check is not set for "is collection".
3. Select more than one checkbox (answer) when answering.

![issue_checkb](https://user-images.githubusercontent.com/113421464/224357926-0d067bf0-f455-4a97-a549-c411a32f5a71.png)

### References / Verweise

* rdmo 1.92

**Comment by jochenklar** [comment]
Indeed, for checkboxes, `is_collection` needs to be checked. This could be set automatically and fixed unless the `widget_type` is changed again to something else.

**Comment by jochenklar** [comment]
This is now validated.
