### ISSUE TITLE
Grammar error in automatically generated help text

### ISSUE THREAD

**Issue by chsinn** [rdmorganiser/rdmo#602]
### Description / Beschreibung

When a collection of objects such as data categories or persons is created, a help text is automatically generated for that. In the generated text the article is sometimes wrong.

![person](https://user-images.githubusercontent.com/113421464/226393793-7cb3390a-0761-4fc9-ad9e-f232f8e1e470.png)
 
-
![dat](https://user-images.githubusercontent.com/113421464/226393866-739c6de0-4889-43fb-bf5a-1495b751fee8.png)

### Expected behaviour / Erwartetes Verhalten

A possibility to define the article itself or the whole text.

### Steps to reproduce / Schritte zum Reproduzieren

Create a question set as a collection where the display name is not "Datensatz".

### References / Verweise

*  rdmo 1.92

**Comment by jochenklar** [comment]
This is actually our oldest open issue: https://github.com/rdmorganiser/rdmo/issues/59
