### ISSUE TITLE
The word title in the popup when creating a collection can not be changed

### ISSUE THREAD

**Issue by chsinn** [rdmorganiser/rdmo#603]
### Description / Beschreibung

When creating a collection such as Person, the popup always says "Title", which is confusing. Here could be "Name" or a user defined name. 
![person_titel](https://user-images.githubusercontent.com/113421464/226560405-027dbafb-ed83-47c0-8770-da5ebf100308.png)

### Expected behaviour / Erwartetes Verhalten

Here could stand name or a user-defined designation. 
Alternatively, the designation "Title" could not appear.

### Steps to reproduce / Schritte zum Reproduzieren

reate a question set as a collection where the display name is not "Datensatz".

### References / Verweise

* rdmo 1.92

**Comment by jochenklar** [comment]
Its "Name" now.
