### ISSUE TITLE
Adjust UI if autosave is true

### ISSUE THREAD

**Issue by m6121** [rdmorganiser/rdmo#604]
### Rationale / Begründung

If the autosave option is set to true, users might be confused about some buttons in the UI.

### Affected 

This mainly effects users.

### Minimal functionality

If the autosave option is set to true, the UI might be adjusted in order to reflect the new workflow. This issue aims at collecting potential changes. In particular the following might be changed:

1. Remove the "Save" button
2. Rename the "Save and proceed" button to "Proceed" or "Next"

**Comment by josp-saxfdm** [comment]
Dem heutigen Look and feel von Web-Anwendungen entspricht die Erwartung dass üblicherweise stetig automatisch gespeichert wird.
Ich würde daher empfehlen, Autosave künftig als Standard zu definieren. 

Die vorgeschlagenen Änderungen der Buttons finde ich auch sinnvoll.
