### ISSUE TITLE
No access via REST api

### ISSUE THREAD

**Issue by stefankusmierz** [rdmorganiser/rdmo#607]
The docu for the REST-api (https://rdmo.ptb.de/api/v1/) generates a X-CSRFToken-Token to get access to RDMO via http-commands. Neither with this token nor with the admin-token (generated within RDMO) access via http is granted (see attachment). Adding username, first_name, last_name etc to the header doesn't change a thing.
Anyone with an idea?

![image](https://user-images.githubusercontent.com/127955801/229526396-beb9ca98-dcd3-4e41-a480-63ebbe48fd79.png)

**Comment by jochenklar** [comment]
Yes, the code in `rdmo-client` is:

```
if token:
    self.headers = {
        'Authorization': 'Token %s' % token
    }
```

**Comment by stefankusmierz** [comment]
Great! The access by token worked! Giving username/password in the header didn't work.

**Comment by jochenklar** [comment]
For basic auth the header needs to be constructed like this: https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side. I never did this myself, I usually use `requests` and the its, e.g. `requests.get(url, auth=(username, password))`.

**Comment by stefankusmierz** [comment]
Thanks for the collaboration, Jochen!
