### ISSUE TITLE
Access to input data

### ISSUE THREAD

**Issue by stefankusmierz** [rdmorganiser/rdmo#609]
How can I get the input data (i.e. the anwers, which users gave to the catalogue questions) via the api?

**Comment by jochenklar** [comment]
Hi @stefankusmierz , if you know the project, you can use `/api/v1/projects/projects/<project_id>/values/` to get all values (i.e. user answers) for the project. If you know the `attribute_id` you can get all answers to that attribute from `/api/v1/projects/projects/values/?attribute=<attribute_id>`. You can get the `attribute_id` from, e.g. `/api/v1/questions/questions/1/`. Endpoints and filters should be available at the swagger interface at `/api/v1/`.

**Comment by jochenklar** [comment]
Some documentation is available here: https://rdmo.readthedocs.io/en/latest/administration/api.html.

**Comment by stefankusmierz** [comment]
Thanks a lot, Jochen. "/api/v1/projects/projects/<project_id>/values/" worked fine. The others return "detail: nicht gefunden". 
But apart from that: my goal is simply to get the list of questions with the given answers. This list already exists within RDMO, because that's exactly the content of an export file. Is there any chance to access the export file (xml or csv would be ok, perfect would be json) via the api?

**Comment by jochenklar** [comment]
We don't have that in the API, but if you use a user/token who can access a project, you can get `/projects/3/export/xml/` also via a script. But i think its better to use the `/api/v1/projects/projects/3/values/` endpoint. You can also get the catalog in a nested way using `/api/v1/questions/catalogs/1/nested/`. Then you just need to connect the values to the questions via the `attribute`.

**Comment by stefankusmierz** [comment]
Perfect, Jochen. Thanks for your help!

**Comment by stefankusmierz** [comment]
Hi,
I have already downloaded the questions and values via the api. I discovered, that under the same attribute there are questions listed various times (each time assigned to distinct questionsets). The answers in turn are only listed with their attributes, but I couldn't find an assignation to a question set. Is there a chance to get this assignation?
The problem is, if I don't know the question set the answer belongs to, I neither can be sure about the text of the related question, because the text of a question depends on the questionset it belongs to.

**Comment by jochenklar** [comment]
Yes, the `Value` also has a `project`, the `project` has a `catalog` and the `catalog` has a `nested` endpoint to get all sections, questionsets and questions.

* `/api/v1/projects/projects/1` has the catalog, e.g. `1`
* `/api/v1/questions/catalogs/1/nested/` has the questions with their attributes.

**Comment by stefankusmierz** [comment]
Ok, thank you, Jochen! That helped!
