### ISSUE TITLE
'views': translation missing | empty fields shown 

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo#62]
When viewing ("Views") a project there exist  inconsistencies:
* chosen German rdmo will show 'none' for an empty field.    
* Despite not being translated the 'none' should not appear at all in the view when empty but where files beforehand), e.g additional author field or rdmo/data-usage/data-sharing-and-re-use/publication  /restrictions_explanation → project/dataset/sharing/restrictions_explanation .

**Comment by jochenklar** [comment]
This was fixed in the "refatoring of 2018".
