### ISSUE TITLE
Set autosave of questions to True by default

### ISSUE THREAD

**Issue by chsinn** [rdmorganiser/rdmo#625]
### Rationale / Begründung

For questionnaires that use autosave & conditions in their design, an autosave that is not activated can cause problems on other RDMO instances because, for example, content that is hidden due to conditions only becomes visible/invisible when the "Save" button is clicked. 
In addition, follow-up questions in such questionnaires do not begin with "If yes, then ...". It's not clear for the user that question xy is still relevant at all.
Questionnaires that do not use autosave & conditions in their design should not have problems of this kind if autosave is activated.
### References / Verweise

* RDMO 1.92

**Comment by jochenklar** [comment]
Idea from @ubbo , save text fields on back and forward.

**Comment by MyPyDavid** [comment]
related PR: https://github.com/rdmorganiser/rdmo/pull/611
