### ISSUE TITLE
Enabling collaborative / parallel work on projects

### ISSUE THREAD

**Issue by chsinn** [rdmorganiser/rdmo#626]
### Rationale / Begründung

If more than one user is working on a RDMO project at the same time, then it can happen that they overwrite each other's responses. 
RDMO does not give a warning message if someone else is working on the project at the same time. 
Sometimes multiple answers are saved, although it should not be possible for the question.

![titel](https://github.com/rdmorganiser/rdmo/assets/113421464/c22e3990-9a6e-49bb-8227-330f2ab7ed30)

For questions with multiple answer options @checkboxes, it can happen that the same answer is saved multiple times.
Input:

![senfb](https://github.com/rdmorganiser/rdmo/assets/113421464/a29da166-2271-4b25-907a-36ab903affb3)

Output in the view:
![sen1](https://github.com/rdmorganiser/rdmo/assets/113421464/5521b745-06e2-4279-bf24-52451fdbc576)

### Minimal functionality

Give a warning that user XY is currently working on the project. One possibility would be to lock the respective question set for editing by other users as long as it is being edited by user XY.

### Nice-to-have functionality

Questions can be answered in a session in which only one user can be present. Other users can take control over the session and get write permissions. This is visible for all users who are currently editing the project.

### References / Verweise

* rdmo 1.92

**Comment by MyPyDavid** [comment]
The merged PR is there, now it should probably be live-tested with/before the next release
