### ISSUE TITLE
Drop support for Python 3.6 and 3.7?

### ISSUE THREAD

**Issue by afuetterer** [rdmorganiser/rdmo#648]
Hi,

not a bug, not a feature, but a question.

Python 3.6. and 3.7 officially reached end of life and do not receive security fixes anymore: https://devguide.python.org/versions/#python-release-cycle
Should the RDMO project recommend upgrading to at least Python 3.8 and drop support for Python < 3.8?

What do you think?

**Comment by MyPyDavid** [comment]
Yes, I agree with dropping support for those. However, recently there was a support request from a user who was still using 3.6 in their deployment. It depends on which deployments are out there I guess...

**Comment by afuetterer** [comment]
I see. I mean, the project could still work on 3.6 and 3.7. But to actively support these EOL versions means to miss out on new features and performance improvements of the evolving language. Also the security patches could be an argument to convince users to update their deployment from unsafe environments?

I see that you are working on a 2.0 release. Maybe that could be used to drop support for EOL versions?

**Comment by afuetterer** [comment]
The pyproject.toml setup proposed in #664 is set to work with Python >= 3.8.
