### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#65]
For some browser configurations, the java script date picker seems to create an invalite date string. The result is 'Invalid date' in `/projects/<id>/answers/`.

**Comment by jochenklar** [comment]
* Firefox, Edge
* Windows 10
* RDMO set to German

**Comment by skelligan** [comment]
I have the same issue on Chrome, too. Even if set to German chosing a date via the date picker generates a date in format MM/DD/YYYY first. After saving and reloading the page the format is DD.MM.YYYY or "invalid date".

**Comment by Zack-83** [comment]
I have the same issue. Maybe you could just set the date format according to ISO (YYYY-MM-DD) regardless of the language...

**Comment by jochenklar** [comment]
This *should* be fiexed in 66d5a3d14d37d93c686874e3bcdbd989c89b2817 and Version 0.11.
