### ISSUE TITLE
allow editors to store alternative view text in options

### ISSUE THREAD

**Issue by jwindeck** [rdmorganiser/rdmo#667]
### Rationale / Begründung
The dfg checklist catalog uses a lot of option sets. Some options contain additional "help" information during the questionaire. This help texts interfere when creating a view, since it is not needed there anyore. In other cases, the wording makes sense during the questionaire, but doesn't fit into the view ouput (e.g. grammar). 

In all theses cases it would help, if editors can store alternative "view text" in an option, which is used in views. If no view text is set, then the default value of the option should be used in views instead.

### Affected 
* Editors, Users

### Minimal functionality
* additional field in option settings for alternative view text

### References / Verweise
* dfg checklist catalog: https://github.com/rdmorganiser/rdmo-catalog/blob/master/rdmorganiser/questions/DFG-Checkliste.xml

**Comment by jochenklar** [comment]
This can be implemented together with https://github.com/rdmorganiser/rdmo/issues/479 and https://github.com/rdmorganiser/rdmo/issues/594.

**Comment by jochenklar** [comment]
It was mentioned that it would be nice that the view text should be visible in the interview. I am not sure how, though. Any ideas @jwindeck @MyPyDavid .

**Comment by jwindeck** [comment]
@jochenklar for our use case it is important that this additional view text is explicitly not shown in the interview. 

If the text is needed for the interview, why not add it directly to the standard field? Maybe I don't get the point here, though

**Comment by jochenklar** [comment]
ok, it could be copy pasted in the help text of the option.
