### ISSUE TITLE
Project creation via API allows for projects without catalog

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#674]
### Rationale / Begründung

We found projects without catalog in our instance.
Project creation should raise a validation error when leaving the catalog empty.

### Affected 

API-Users

### Minimal functionality

* a validation error should be given when catalogs is `null` 

### References / Verweise

* POST to `/api/v1/projects/projects/" `
* https://github.com/rdmorganiser/rdmo/issues/593

**Comment by jochenklar** [comment]
The problem is that the catalog in the `Project` model can be `None`, e.g. when the catalog was deleted. I fixed the serializer to correctly validate the catalog field and also check for catalog availability.

**Comment by jochenklar** [comment]
Fixed in https://github.com/rdmorganiser/rdmo/releases/tag/2.0.0
