### ISSUE TITLE
Change/split test settings setup

### ISSUE THREAD

**Issue by afuetterer** [rdmorganiser/rdmo#690]
### Rationale / Begründung

Can the test settings testing/config/settings be set up differently? It is a little difficult to wrap your head around the settings setup. 

### Affected 

Tests.

### Minimal functionality

I propose the following setup:
- base settings
- dev settings for local development
- testing settings for running the unit tests

Remove the mysql, postgres, sqlite modules and choose the database backend from an env variable.

What do you think?

### References / Verweise

Similar to:
* https://github.com/rdmorganiser/rdmo-app/issues/11

**Comment by jochenklar** [comment]
Hey @afuetterer , I updated the settings to make them similar to the new `rdmo-app` (with an identical `testing/config/settings/__init__.py`) and put the database config in `testing/config/settings/base.py` based on a environment variable `GITHUB_DB_BACKEND`.
