### ISSUE TITLE
Create a new branch to collect the dependabot PRs

### ISSUE THREAD

**Issue by afuetterer** [rdmorganiser/rdmo#691]
### Rationale / Begründung

As proposed in #682, the dependabot can submit PRs to any existing target branch in the repository. It does not have to be the master branch.
If the PRs to master do not fit the workflow of the rdmo team. You could create a new branch, that is used to gather the dependabot PRs and merge this branch periodically.

Name variants could be:
- dependabot
- dependabot-updates
- dependencies
- dependency-updates
- deps
- develop
- dev
- ...

I would suggest `dependency-updates`. It is clear and transports the purpose of the branch.

Dependabot config needs to updated then to include:
`target-branch: <dependency-updates>`

What do you think?

### Affected 

Software team.

### References / Verweise

* #682

**Comment by jochenklar** [comment]
I also like `dependency-updates`. It can then merged to the current development branch from time to time.

**Comment by afuetterer** [comment]
Could you create such a branch? I will update the config accordingly.

**Comment by jochenklar** [comment]
I created `dependency-updates` from `dev-2.0.0`.
