### ISSUE TITLE
Housekeeping: Need for jsonfield dependency

### ISSUE THREAD

**Issue by afuetterer** [rdmorganiser/rdmo#692]
Hi,

with every CI run and every rdmo installation, we install the third-party dependency `jsonfield`. This dependency was used in two model fields in the beginning of the project. It is only imported in two migration files that date back a few years:
See: https://github.com/search?q=repo%3Ardmorganiser%2Frdmo%20jsonfield&type=code

These models were deleted in future migrations. So basically the dependency is not needed anymore. If you remove it, the migration process will break.

One suggestion would be to squash some early migrations. What do you think?

**Comment by MyPyDavid** [comment]
yes, but maybe wait for what @jochenklar will say about this

**Comment by afuetterer** [comment]
Yes, sure. It is just an idea or an observation: Why install jsonfield, if it is not needed anymore.

**Comment by jochenklar** [comment]
I would not squash the migrations, we don't know what RDMO instances are out there. I also don't think this is a very big problem.
