### ISSUE TITLE
Typo in german task email address

### ISSUE THREAD

**Issue by tgnadt** [rdmorganiser/rdmo#702]
### Description / Beschreibung

When sending a task via email, the email in german starts with "Sehr geerte Damen und Herren,"

### Expected behaviour / Erwartetes Verhalten

The email should start with "Sehr geehrte Damen und Herren,"

### References / Verweise

* probably needs to be fixed here:
https://github.com/rdmorganiser/rdmo/blob/master/rdmo/locale/de/LC_MESSAGES/django.po#L2871

**Comment by afuetterer** [comment]
Thank you for reporting this.

**Comment by jochenklar** [comment]
Will be fixed in the next release (later this week).
