### ISSUE TITLE
Question help needs changing: "person" referred to as "item" multiple times - RDMO, DFGv5 catalog

### ISSUE THREAD

**Issue by sa-wetter** [rdmorganiser/rdmo#703]
Hi,

I have come across this bug multiple times. I am working with the RDMO, the brief questionnaire and DFGv5 catalog.

in the RDMO catalog: a question is e.g. asking for persons/institutions involved in the project coordination and the question help then refers to them as "items".
<img width="1203" alt="items instead of names" src="https://github.com/rdmorganiser/rdmo-catalog/assets/141029341/84172c79-cd36-4cb2-83e2-d7474282a28a">

Here an example from the DFGv5 catalog:
<img width="911" alt="special_responsibility" src="https://github.com/rdmorganiser/rdmo-catalog/assets/141029341/97289d17-7532-4628-ba4e-908867fa4a6d">

I know this is tedious, but someone should look into this. People, institutions, project partner etc. are not items. However, this bug is also not consistent since many times this specific question help is actually also fine (-> first screenshot: top question gets the "disciplines" right). Maybe the word "items" can be a variable, depending on the question. Or if it is already a variable then its value is not assigned correctly.

Best,
Sarah

**Comment by jochenklar** [comment]
@Zack-83 I think this is a problem in the catalog not in the code. `vebose_name` and `verbose_name_plural` are not set in the xml files, I guess.

**Comment by Zack-83** [comment]
OK, wir kümmern uns darum https://github.com/rdmorganiser/rdmo-catalog/pull/206/files

@sa-wetter : Kannst du bitte weiter editieren? Der RDMO-Katalog ist in [/rdmorganiser/questions](https://github.com/rdmorganiser/rdmo-catalog/tree/703-question-help-needs-changing-person-referred-to-as-item-multiple-times-rdmo-dfgv5-catalog/rdmorganiser/questions) und der DFG-Katalog in [/shared/ub_fau_erlangen_nuernberg](https://github.com/rdmorganiser/rdmo-catalog/tree/703-question-help-needs-changing-person-referred-to-as-item-multiple-times-rdmo-dfgv5-catalog/shared/ub_fau_erlangen_nuernberg)

@jochenklar : Kannst du uns bitte lotsen? Betrifft das alle Fragen mit `<is_collection>True</is_collection>`?
Lohnt es sich bis zum Erscheinen der Version 2.0 abzuwarten, als die Kataloge modular aufgebaut sein werden?

**Comment by sa-wetter** [comment]
@Zack-83 mach ich.

**Comment by sa-wetter** [comment]
So wie es aussieht ist das ganze etwas komplizierter: ich habe es auf einem Testserver mal geändert und bin auf einen Fehler gestoßen.
Im Bild zwei Beispiele.
<img width="889" alt="Screenshot 2023-09-21 at 15 57 37" src="https://github.com/rdmorganiser/rdmo/assets/141029341/69cb6172-40b0-41d4-a520-7de5a7278c1a">

Wenn die `verbose_name` und `verbose_name_plural` für Objekte wie "Schlagwort" benutzt werden, macht der Satz Sinn. Wenn man allerdings nach Namen und fragt, dann muss man die Grammatik beachten und dann kommt es zu Fehlern. 
Da in beiden Sätzen das `verbose_name_plural` benutzt wird, aber im zweiten der Fall manchmal beachtet werden muss. 

Fällt euch etwas ein?

**Comment by jochenklar** [comment]
Ja, das ist genau das Problem das ich im Meeting meinte: https://github.com/rdmorganiser/rdmo/issues/59 und https://github.com/rdmorganiser/rdmo/issues/602. Ich werde da demnächst dran arbeiten, und es soll Teil von RDMO 2.1.0 werden.

**Comment by sa-wetter** [comment]
@jochenklar  ich lasse meinen Vorschlag mal hier stehen, bevor ich ihn wieder vergesse: 
"Bitte nutzen Sie für die Schlagwörter/Verantwortlichen jeweils eine Zeile. Mit dem grünen Button können Sie weitere hinzufügen und mit dem blauen Kreuz (wieder) entfernen." Somit entfällt zumindest das Problem im zweiten Satz. Ich schaue mal, bei welchen Fragen/ `verbose_name_plural` das doch nicht klappt. Bei den Fragen auf Englisch gäbe es zumindest keine Probleme.

**Comment by jochenklar** [comment]
Ja, vll nutzen wir einfach das Issue hier um das durchzudiskutieren. Ich glaube langsam auch das wir eher eine generische Formulierung finden sollten anstatt das anpassbar zu machen. Noch mehr Felder wie `verbose_name` macht es einfach noch komplizierter Kataloge zu bearbeiten. Vll werden wir ja `verbose_name_plural` auch noch los.

**Comment by jochenklar** [comment]
Das einfachste wäre, wenn wir `verbose_name_plural` entfernen, und `verbose_name` nur für die Buttons benutzen. Die grauen Hilfetexte könnten wir generisch Formulieren (aber mit entry statt item. Also:

> Please enter the items line by line. You can add items using the green button and remove them using the blue cross (×).

> Bitte nutzen Sie für die Einträge jeweils eine eigene Zeile. Sie können weitere Einträge mit dem grünen Button hinzufügen und mit dem blauen Kreuz (×) entfernen.

Bei dem Hilfetext für die Page-collections ist das nicht so gut machbar:

> Bitte füllen Sie das Formular für jeden Eintrag aus. Die verschiedenen Einträge werden eventuell in späteren Fragen wieder verwendet. Sie können einen neuen Eintrag mit dem grünen Button hinzufügen. Bereits angelegte Einträge können mit den Buttons oben rechts bearbeitet oder wieder entfernt werden.

klingt nicht passend.

Ein Problem ist auch das der `verbose_name` eigentlich auch nicht reicht. Wenn ich "Person hinzufügen" auf Französisch übersetze, dann bekomme ich "Ajouter une personne" nicht "Ajouter personne", also mit Artikel. Das deutet eher darauf hin das es mit dem zusammensetzen von `verbose_name` und template-Übersetzung nie zufriedenstellend funktionieren wird.

**Comment by jochenklar** [comment]
Hier nochmal die Liste wo `verbose_name` und `verbose_name_plural` vorkommen:

* add field button (question)
* add field help (question, plural, probably buggy)
* add set button (question, should be questionset?)
* add set help (question, plural, should be questionset?, probably buggy)
* delete value set (page)
* value set form (page)
* questionset head (page)
* questionset head help (page, this issue)
* remove field (question)
* remove set (page)

**Comment by jochenklar** [comment]
Ok, jetzt habe ich eine Idee: generische Hilfetexte und Symbole auf den Buttons und nur noch `verbose_name`.

Siehe:

![Screenshot 2023-09-29 at 19-05-22 example com](https://github.com/rdmorganiser/rdmo/assets/1799675/510ee4bc-328c-4299-8718-20896eebea51)

![Screenshot 2023-09-29 at 19-15-51 example com](https://github.com/rdmorganiser/rdmo/assets/1799675/bd2e1a89-3253-4b68-ab3c-ebc0937b018c)

**Comment by sa-wetter** [comment]
@jochenklar das ist eine richtig gute Idee!

**Comment by Zack-83** [comment]
Teilweise in https://github.com/rdmorganiser/rdmo-catalog/pull/206 , teilweise durch Umstrukturierung in RDMO2.0 gelöst
