### ISSUE TITLE
Add `double-quote-string-fixer` to pre-commit-config

### ISSUE THREAD

**Issue by afuetterer** [rdmorganiser/rdmo#713]
### Rationale / Begründung

I use double quotes in my projects nowadays, because `black` convinced me. It is hard to switch back mentally. This project uses mostly single quotes, but not consistently. There is hook called `double-quote-string-fixer` that replaces double quoted strings with single quoted strings. Should we add this to the pre-commit-config? That way, it gets fixed automatically.

What do you think?

### Affected 

devs

### References / Verweise

- https://pre-commit.com/hooks.html

**Comment by MyPyDavid** [comment]
we had some discussions about this on the hackathon 🤣 
see: https://rdmo.slack.com/archives/C050KFAQ79D/p1691675566585859
For me, the single quotes also look a bit weird
but when Guido uses single quotes, then I'm also convinced

**Comment by afuetterer** [comment]
Fine, I see. So it is consensus to use single quotes.
Should I add the hooks to enforce them (on me)?

**Comment by jochenklar** [comment]
I am totally fine when other people use double quotes. I would say there is no need to enforce them.

**Comment by afuetterer** [comment]
Alright, my argument was for consistency in the project. No pre-commit-hook then, that is fine for me.
