### ISSUE TITLE
Please update django to current security release 1.11.11 

### ISSUE THREAD

**Issue by luh-luis-css** [rdmorganiser/rdmo#73]
According to Django Security Release https://www.djangoproject.com/weblog/2018/mar/06/security-releases/ the actual in rdmo used version 1.11.1 is vulnerable to  Denial-of-service attacks or something like that. 

cu Reik

**Comment by jochenklar** [comment]
Thanks for posting, we already fixed that in the master branch, but did not publish a new version yet. This will happen this week.

**Comment by jochenklar** [comment]
It took a bit longer than a week, but the fix is now in the 0.10 release.
