### ISSUE TITLE
Question about GitHub labels

### ISSUE THREAD

**Issue by afuetterer** [rdmorganiser/rdmo#737]
Some of the custom labels in this repository have a space in them, other don't.
For example:
- [type: maintenance](https://github.com/rdmorganiser/rdmo/labels/type%3A%20maintenance)
- [effort:huge](https://github.com/rdmorganiser/rdmo/labels/effort%3Ahuge)

I saw that I used "type:maintenance" for the dependabot config, because I did not see the space. Now it fails to label its PRs.

Where should we fix here? Rename the label or change the dependabot config?

**Comment by MyPyDavid** [comment]
I'm not sure, is `type: maintenance` or `type:maintenance` more readable in the issues page? 
I would say without space, so to remove the space from the labels

**Comment by afuetterer** [comment]
I don't really care, I just wanted to point it out, after seeing the dependabot complaining.
Maybe go for `type:maintenance` then like you suggest?

Can you rename a label? Feel free to close then.

**Comment by MyPyDavid** [comment]
thanks! Ive renamed the labels and removed the whitespaces! so the dependabot config can stay the same
