### ISSUE TITLE
Usage of keys for multiple options to make script language-independent

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo#74]
When a variable possessing an optionset is used as a condition, the result is depending on the language:
ex. to check if the licence is "share-alike", only one of these will work:
either {% if values.project.dataset.sharing.conditions == "Share-alike (SA)" %}
or {% if values.project.dataset.sharing.conditions == "Weitergabe unter gleichen Bedingungen (SA)" %}
Moreover, the strings to search are quite verbose.
Is it possible to recall the key, or the URI, of the value? (in this case "75")

Dankeschön
Giacomo

![share-alike](https://user-images.githubusercontent.com/37865804/38088948-0f91bf42-335e-11e8-8e05-b31e281ee9b1.png)

**Comment by jochenklar** [comment]
Thanks for posting, we will fix that. There will be a new version of rdmo this week.

**Comment by Zack-83** [comment]
To make it more clear: options should contain
- a short "key", invisible to the user, which is available for comparison or application of conditions, i.e. for the {% ... %} fields of the Django template;
- a long "verbose text" / "help text", in English and German, which appears in the question catalogue, in order to support the user in choosing the suitable answer;
- an "output text", which is adapted to the language flow of the desired output template (this is output-specific and can also be generated directly in the Django template).

**Comment by Zack-83** [comment]
OK, what I wanted is solved applying a condition within the view https://rdmo.readthedocs.io/en/latest/management/views.html#render-values
