### ISSUE TITLE
Add order parameter back to managament interface

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#745]
### Rationale / Begründung

The order parameter of the elements (more precice: of the m2m entries between the elements) is not shown in the interface should we add it again?

### Affected

Managers, Admins

**Comment by MyPyDavid** [comment]
this might be helpful for debugging https://github.com/rdmorganiser/rdmo/pull/751. 
The number maybe after the title text or in right bottom corner of panel?
