### ISSUE TITLE
error in link leading to single project in admin view

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo#76]
Hallo,
a very practical function of RDMO allows the main administrator to get access to alll projects over "admin" -> "projects" -> <name of the project>
Yet after clicking "Auf der Webseite anzeigen" a nonvalid link is produced, with too many slashes and https strings: ex. https://https//rdmo.ptb.de//projects/2/ (in my local instance)
Of course i can correct the link by hand, but maybe the issue can be centrally fixed with few effort.
Bye
Giacomo

**Comment by jochenklar** [comment]
Hi, i was not even aware of his function. It is indeed practical. The link is constructed using the [site config in the Django backend](http://rdmo.readthedocs.io/en/latest/administration/site.html). I think your problem will be fixed by removing `https://` from the domain name.

**Comment by Zack-83** [comment]
You are right, it was easier than i thought. I had just to remove `https://` and the trailing `/` from the _Site_ name (i.e. write `rdmo.ptb.de` instead of `https://rdmo.ptb.de/`). Dankeschön!
