### ISSUE TITLE
Add pre-commit autoupdate CI job

### ISSUE THREAD

**Issue by afuetterer** [rdmorganiser/rdmo#777]
### Rationale / Begründung

I propose adding a CI job, that runs using a cron job (once per month like the dependabot?), and updates the pre-commit hooks config. What do you think?

### Affected

devs

### Minimal functionality

The job should run
```
pre-commit autoupdate
```
check, if the `.pre-commit-config.yaml` changed, if yes, commit it and create a PR.

https://pre-commit.ci/ does this automatically, but I guess we don't need another service involved.

### References / Verweise

* https://pre-commit.com/#pre-commit-autoupdate
* https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by jochenklar** [comment]
Good idea! I would also be fine with the pre-commit service, but I should only create PR to `update-dependencies` or somethin similar which we then merge into `dev-*`.

**Comment by afuetterer** [comment]
I could provide a custom GitHub action for rdmo.

But if you prefer, we can use https://pre-commit.ci/ as well. I have not used it before, but a lot of projects use it, it is from the author of pre-commit itself. They can do the linting for us as well then. They say it is really fast.
