### ISSUE TITLE
Uploading an empty file crashes RDMO

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#784]
### Description / Beschreibung

Uploading an empty file crashes RDMO and you don't even get a response. Not sure why.

### Steps to reproduce / Schritte zum Reproduzieren

1. Go to `/projects/`
2. Click on 'Select file' (under "Import from file")
3. Select an empty file
4. "This site can’t be reached"

### Context / Kontext

Chromium and Firefox on Debian 11

**Comment by MyPyDavid** [comment]
can not reproduce this, I only get this:

> Import error
> Files of this type cannot be imported.
>

**Comment by MyPyDavid** [comment]
The current dev-2.2.0 with the new projects overview does not crash for when import fails.
It just does not show anything about the failure, the request returns a 400.

Is this issue resolved like this or you wanna add some error handling on the import at `/projects`?

**Comment by jochenklar** [comment]
I think/hope it's resolved :smile:
