### ISSUE TITLE
Set order for multiple different Tasks

### ISSUE THREAD

**Issue by RH-DIPF** [rdmorganiser/rdmo#797]
### Rationale / Begründung

Currently Tasks are just in a "random" order in the project. (The tasks that was last changed (from "open" to "closed" etc) is at the bottom. But besides that, i appears to be random). 
It would increase the usability (of Tasks) immensly if Managers had some way to influence in what orders Users will see the tasks. 

### Affected

Managers and Users 

### Minimal functionality

A "global order parameter" would be nice. All in all similar to the way Managers can now set the order of different catalogs. Tasks would be in the same order across all projects/catalogs. Setting a different order for every catalog is probaly unnecessary

### Nice-to-have functionality

Open tasks always on top, closed tasks always at the bottom would also be nice. Maybe "brackets" inside the Tasks-List for open, in progress and closed tasks? Probaly a different issue. 

### References / Verweise

*

**Comment by jochenklar** [comment]
Hi @RH-DIPF, thanks for the issue. Totally makes sense and nondeterministic order of the tasks is even a bug. I will try to fix it for the next release.
