### ISSUE TITLE
broken import zwischen 0.9.5 und 0.10.1 

### ISSUE THREAD

**Issue by BlackLotus** [rdmorganiser/rdmo#80]
Ein bisect von rdmo zeig, dass einer der folgenden commits den import der Kataloge zerschossen hat.
Wie man es repdouzieren kann:
In 0.9.5 kann man alle Kataloge importieren (inklusive die agfdm.xml Datei die ich hier Anhänge) und dann ein Projekt mit dem AGFDM Katalog erstellen.
(Der AGFDM Katalog ist eine ältere Version einer noch WIP-Arbeit)
Bei der zweiten Frage kann man dann eine Forschungsdisziplinen auswählen.
Wenn man das ganze mit einer neueren Version probiert ist das Dropdown-Menü leer.
Ein Bisect hat gezeigt, dass das Problem wahrscheinlich in einem dieser Commits sich eingeschlichen hat

> 093b4d8f8a8e5ba4fb3fc8fbb157fbe88a36dad1
> 6a54dc9318b9ce42f386e8a50a3dd37c12ac9838
> 497f4f29d1c5c4fb0afefe95068272020b1e1cf7
> 603712db0855cded0d9b4495b4d8e99fb2bdc536
> 498ef0a55a7568077873b143c599870b9f580921
> e0bc30de1dc07794a2838060ab14a74f7b6bd023
> 2bf8c58a0254c87fea7da560acf9483f58a2f001
> 4ffd9d7d6d9a2e01363507edaca72f10fd239a10
> 112d9840903ed49b73aa45c2221ff68dc70e12c2
> ab3dc09cb9fbf58eedc86f2bb7f8972229751959
> 3905edc62088f833828bb2e2893554228bd7e859
> c8638dc7dfec597a7936b0af2eb6d6c6fd7a76b8
> 943d635e498dd1c3042c531683b8f1e774be32ca
> b9130a9c556f07a14c5a1e530c00eb41f8d9b38b
> c46cbc254f2536a30b3ca127424078ff88d6e010
> dfbe20734bd6df41e606f9481900d7036a1365e8
> 3646b42d286ab163d80566080ded2b44f726c4c9
> eba712a93ad39e2002ea636627df61cfb364ce44
> 0888debee052cb3ca4afe4cbb08ea0bfc7db0d4f
> 56ef0b35e0092cd6e8d49a593e40c109b98b41cc
> 5aed7216035910f3fb78d0e0cfba27f84f2d9a44
> b3bd7c188157dd350fd35aab55ff19e3fcd71958
> c3e287eaefebf0abd6508ff8449077b8301c0d62

Ich konnte das ganze nicht genauer eingrenzen da der gesamte Import-Prozess oder die Anzeige der Fragen häufig kaputt war. 

Hier die oben genannte agfdm.xml
https://gist.github.com/eb902f524a4f2a1472aec2d60b2049d5

**Comment by jochenklar** [comment]
Danke für den Hinweis, wir werden der Sache zeitnah nachgehen.

**Comment by BlackLotus** [comment]
Danke erstmal für die Info.
Mir ist gerade aufgefallen habe das missverständlich formuliert. Der Fehler wurde eingeführt zwischen 0.9.5 und 0.10.1 aber er existiert noch in 0.10.3

**Comment by triole** [comment]
Das Problem beim Katalog-Import ist Ergebnis zweier Dinge.

1. Es gab einen Fehler im Code, der dafür sorgte, dass Fragen nicht importiert wurden. Er sollte durch die letzten Commits behoben sein.

2. Im XML gibt es seltsamerweise Differenzen zwischen der URI des Catalogs und denen der Fragen. In der Catalog-URI ist der Catalog mit "agfdm" benannt. In den Fragen steht "rdmo" (siehe unten). Dieser Unterschied sorgt dafür, dass Fragen nicht richtig zugeordnet werden können.

Catalog-UR : https://rdmorganiser.rub.de/terms/questions/agfdm
Fragen-URI: https://rdmorganiser.github.io/terms/questions/rdmo/general/topic

Hier eine korrigierte Version der XML-Datei: [agfdm-fix.xml.zip](https://github.com/rdmorganiser/rdmo/files/2057711/agfdm-fix.xml.zip)

Außerdem haben wir festgestellt dass, ein erneuter Import eines bereits vorhandenen Katalogs zu Problemen führen kann. In einigen Fällen wurden Elemente doppelt importiert. Wir arbeiten an einem Fix dafür. Bis wir eine Lösung gefunden haben, können Schwierigkeiten umschifft werden, indem der vorhandene Katalog vor Import per Hand entfernt wird.

**Comment by jmfrenzel** [comment]
Sehe ich das richtig, beim Entfernen eines Katalogs gehen alle die Projekte "verloren", welche den diesen benutzen?

**Comment by triole** [comment]
@jmfrenzel Danke für den absolut berechtigten Hinweis. Es verhielt sich tatsächlich so, dass Projekte deren Fragenkatalog entfernt wurde, ebenfalls gelöscht worden sind. Das Verhalten haben wir verändert. 

Projekte bleiben nun erhalten, wenn dazugehörige Fragenkataloge gelöscht werden. Logischerweise ist solchen Projekten dann jedoch kein Fragenkatalog mehr zugewiesen. Die Zuweisung eines Kataloges muss anschließend manuell vorgenommen werden.
