### ISSUE TITLE
Improvement of the export functionality

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo#81]
The exported DOCX and ODT files are in "Letter" format. Please change it into the standard A4!

The exported TEX files are without the preamble. Indeed, depending on the complexity of the formatting, they might require some special packages. Please make so that a preamble is produced!

(Optional: The exportex XML files are one-liners. Would it make sense to output them with line breaks?)

**Comment by jochenklar** [comment]
Was fixed in 8ac84f41de07ffe9c748975236fe31a5c65e0fe0.
