### ISSUE TITLE
add the django-shibboleth-remoteuser fork to pyproject.toml

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#828]
we can make our own release on the fork and include it in the `pyproject.toml`
```toml
shibboleth = [
  "django-shibboleth-remoteuser @ https://github.com/rdmorganiser/django-shibboleth-remoteuser/archive/refs/tags/v0.11.zip"
]
```
... that works
* https://packaging.python.org/en/latest/specifications/dependency-specifiers/

_Originally posted by @MyPyDavid in https://github.com/rdmorganiser/rdmo/issues/77#issuecomment-1804062027_

**Comment by afuetterer** [comment]
How about this?

```toml
"django-shibboleth-remoteuser@git+https://github.com/rdmorganiser/django-shibboleth-remoteuser@v0.11"
```

**Comment by jochenklar** [comment]
Removed again since PyPI does not support it :disappointed:
