### ISSUE TITLE
Missing translations in the management interface

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmo#829]
### Description / Beschreibung

In the German management view, the buttons are expressed in a mixture of German and English:

![grafik](https://github.com/rdmorganiser/rdmo/assets/37865804/16bd3994-0c8c-44cf-8d19-62740ccd9d71)

### Expected behaviour / Erwartetes Verhalten

Full German localisation would be better: "Existierenden Abschnitt hinzufügen", "neuen Abschnitt erstellen"

**Comment by jochenklar** [comment]
Thanks! Already on it https://github.com/rdmorganiser/rdmo/pull/826.
