### ISSUE TITLE
[docs] wrong env path for systemd?

### ISSUE THREAD

**Issue by Commifreak** [rdmorganiser/rdmo#836]
### Description / Beschreibung

Setting up rdmo 2.0.2 with a new env using the systemd method (https://rdmo.readthedocs.io/en/latest/deployment/gunicorn.html#systemd) fails with "No module named 'gunicorn'" when using the rdmp-apps env folder. Since the env is being deployed one level up, I am curious if the docs have a typo?

Instead `Environment=GUNICORN_BIN=/home/rdmo/rdmo-app/env/bin/gunicorn` I set it to `Environment=GUNICORN_BIN=/home/rdmo/env/bin/gunicorn` which is working. I still have an env folder inside the rdmo-app but I assume thats from pre-2 verions? Anyway, I dont see any file touches since moving to a new server and upgrading it to v2. The primary env folder is located on the same level as rdmo-app.

So, docs typo/outdated or am I setup something wrong?

### Context / Kontext

Ubuntu 22.04.3
Python 3.10
RDMO 2.0.2 with gunicorn / systemd / nginx

### References / Verweise

*

**Comment by jochenklar** [comment]
Hi @Commifreak , the `env` directory is usually in the `rdmo-app` directory (if you follow our documentation): `/srv/rdmo/rdmo-app/env`. There is nothing wrong with creating the environment somewhere else, but the paths have to be adjusted. You can also use a relative path like `Environment=GUNICORN_BIN=env/bin/gunicorn` if `WorkingDirectory` is set correctly.

**Comment by Commifreak** [comment]
Good to know. I found another "bug" with the new systemd file, placing the sock files at /run/gunicorn/rmdo.sock: Its not working after a reboot. the sock file along with its parent directory `gunicorn` is not being created. A manual `service rdmo restart` did the trick but after a reboot its not automatically creating the sock folder path. But systemd is telling me, gunicorn is running, but its not. Weird.

**Comment by Commifreak** [comment]
Ahh. It has something todo with multi site setup. I again have multiple service files but with the same WorkignDirectory. That seems to mess things up. Si I _think_ multi site is messing with the new systemd file. I, testing things out currently.

**Comment by Commifreak** [comment]
Done. One has to set different `RuntimeDirectory` for each instance. The same could lead to removal upon failing services.

`RuntimeDirectory=gunicorn3` with adaptation of the socket paths below did the trick for us.

**Comment by jochenklar** [comment]
Interesting, so you have multiple systemd service files with the same `RuntimeDirectory` and the automatic creation does not work? If so I will add a note in the documentation. I actually makes sense to have seperate logs for the different services, but not nessesarily seperate directories. I would use `/run/gunicorn/site1/`, `/run/gunicorn/site2/` I guess.

**Comment by Commifreak** [comment]
My systemd service definitions currently look like:

```
[Unit]
Description=RDMO gunicorn daemon
After=network.target

[Service]
User=rdmo
Group=rdmo

WorkingDirectory=/home/rdmo/rdmo-app
RuntimeDirectory=gunicorn
LogsDirectory=gunicorn rdmo

Environment=GUNICORN_BIN=/home/rdmo/env/bin/gunicorn
Environment=GUNICORN_WORKER=3
Environment=GUNICORN_TIMEOUT=30
Environment=GUNICORN_BIND=unix:/run/gunicorn/rdmo.sock
Environment=GUNICORN_PID_FILE=/run/gunicorn/rdmo.pid
Environment=GUNICORN_ACCESS_LOG_FILE=/var/log/gunicorn/access.log
Environment=GUNICORN_ERROR_LOG_FILE=/var/log/gunicorn/error.log

ExecStart=/bin/sh -c '${GUNICORN_BIN} \
  --workers ${GUNICORN_WORKER} \
  --timeout ${GUNICORN_TIMEOUT} \
  --bind ${GUNICORN_BIND} \
  --pid ${GUNICORN_PID_FILE} \
  --access-logfile ${GUNICORN_ACCESS_LOG_FILE} \
  --error-logfile ${GUNICORN_ERROR_LOG_FILE} \
  config.wsgi:application'

ExecReload=/bin/sh -c '/usr/bin/pkill -HUP -F ${GUNICORN_PID_FILE}'

ExecStop=/bin/sh -c '/usr/bin/pkill -TERM -F ${GUNICORN_PID_FILE}'

[Install]
WantedBy=multi-user.target
```

2nd:

```
[Unit]
Description=RDMO gunicorn daemon
After=network.target

[Service]
User=rdmo
Group=rdmo

WorkingDirectory=/home/rdmo/rdmo-app3

LogsDirectory=gunicorn rdmo
RuntimeDirectory=gunicorn3

Environment=GUNICORN_BIN=/home/rdmo/env/bin/gunicorn
Environment=GUNICORN_WORKER=3
Environment=GUNICORN_TIMEOUT=30
Environment=GUNICORN_BIND=unix:/run/gunicorn3/rdmo.sock
Environment=GUNICORN_PID_FILE=/run/gunicorn3/rdmo.pid
Environment=GUNICORN_ACCESS_LOG_FILE=/var/log/gunicorn/access3.log
Environment=GUNICORN_ERROR_LOG_FILE=/var/log/gunicorn/error3.log

ExecStart=/bin/sh -c '${GUNICORN_BIN} \
  --workers ${GUNICORN_WORKER} \
  --timeout ${GUNICORN_TIMEOUT} \
  --bind ${GUNICORN_BIND} \
  --pid ${GUNICORN_PID_FILE} \
  --access-logfile ${GUNICORN_ACCESS_LOG_FILE} \
  --error-logfile ${GUNICORN_ERROR_LOG_FILE} \
  config.wsgi:application'

ExecReload=/bin/sh -c '/usr/bin/pkill -HUP -F ${GUNICORN_PID_FILE}'

ExecStop=/bin/sh -c '/usr/bin/pkill -TERM -F ${GUNICORN_PID_FILE}'

[Install]
WantedBy=multi-user.target
```

This is working. MultiSite with multi systemds with SAME RuntimeDir is not working.

**Comment by jochenklar** [comment]
Ok thanks, good to know.
