### ISSUE TITLE
Shibbolth and other authentification systems

### ISSUE THREAD

**Issue by leucoryx** [rdmorganiser/rdmo#85]
It hsoul dbe possible to allow new accounts and/or other authentification systems combined with shibboleth.

**Comment by jochenklar** [comment]
The recomended aproach for this is now to use https://www.keycloak.org as authenfication system, and the corresponding django-allauth provider: https://django-allauth.readthedocs.io/en/latest/providers.html#keycloak (thanks to @MyPyDavid). Closing here.

**Comment by jochenklar** [comment]
This is now also possible using the new Shibboleth setup.
