### ISSUE TITLE
filter in managment should be case insensitive

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo#858]
### Rationale / Begründung

An editor wants to filter catalogs.

### Affected

Editors

### Minimal functionality

* make filter case insensitve

### Nice-to-have functionality

* "Match case" toggle in search box

### References / Verweise

*

**Comment by jochenklar** [comment]
Makes sense, but I would argure against more interface elements. Case insensitive search ist fine.

**Comment by MyPyDavid** [comment]
yes, the nice-to-have is only what would still be possible in the search box.
Ive added the PR
