### ISSUE TITLE
Endpoint for catalogs for all projects overview table

### ISSUE THREAD

**Issue by CalamityC** [rdmorganiser/rdmo#864]
### Rationale / Begründung

For refactoring the projects with react/javascript an API fetch of catalogs is needed.

### Affected

All

### Minimal functionality

What functionality would you like to have?
API endpoint to fetch all catalogs (at least available for superusers and managers), for "all Projects View".

### Nice-to-have functionality

What sort of related functionality would you like to see in addition?

### References / Verweise

*

**Comment by jochenklar** [comment]
Will be part of 2.2.0.
