### ISSUE TITLE
Improve usability to create question catalogs

### ISSUE THREAD

**Issue by leucoryx** [rdmorganiser/rdmo#87]
- easier change of question order (not be memorizing order number)
- less number of sides
- links of questions and option sets should be visible from both sites

**Comment by jochenklar** [comment]
The third point is solved in addffba4d6f555d46a79384faad9deaa3fad5890.

**Comment by jochenklar** [comment]
As of RDMO 1.4 the order number is displayed in the list view.

**Comment by jochenklar** [comment]
Unless we refactor the whole management interface, no further improvement can be done here.

**Comment by MyPyDavid** [comment]
the whole management interface is refactored. 

The order is editable by drag&drop
> * easier change of question order (not be memorizing order number)  

The order will be displayed again with this [PR](https://github.com/rdmorganiser/rdmo/pull/790)

What is meant by these points? (single page?)
> * less number of sides
> * links of questions and option sets should be visible from both sites

**Comment by jochenklar** [comment]
I think that was about the 6 different management pages. Can stay closed.
