### ISSUE TITLE
import functionallity for DMP content

### ISSUE THREAD

**Issue by hgoerzig** [rdmorganiser/rdmo#89]
As discussed at the RDMO community meeting it would be great to have an import functionality from other data sources, as instrument or administrative data bases.
The workflow would be:
- User creates a project
- Selects to import data
- Selects data source
- Inserts administrative identifier for external system
- RDMO sends request to external system
- Retrieves answers/values for corresponding questions/attributes 
- Inserts answers/values in database for RDMO project

Requirement for usage would be that the RDMO using institution creates an API and a mapping from its data sources to RDMO attributes.

**Comment by jochenklar** [comment]
Using the new plugin-system (https://rdmo.readthedocs.io/en/latest/configuration/plugins.html) custom import from file can be developed. The next step would be adding web service based import plugins. Sadly, no time frame for this.
