### ISSUE TITLE
Element duplication

### ISSUE THREAD

**Issue by chsinn** [rdmorganiser/rdmo#890]
### Element duplication 

This incidence occurs during application of the integrated copy function in RDMO. During the duplication process, the new element inherits without consultation all relations of the original element.

This behaviour might be intended, if existing option sets should be extended. But it is confusing, if an option from set B is copied to be used in another option set B' similarily. After the duplication process is complete, option set B carries both option A and A'.

This incidence is not restricted to options and option sets and can be reproduced for instance with attributes too. With regard to the multi-site-setup this incidence may create some confusion unintentionally.

![1](https://github.com/rdmorganiser/rdmo/assets/113421464/79f1cc2b-f4ca-4713-97d6-60239678f48d)

![2](https://github.com/rdmorganiser/rdmo/assets/113421464/c511aa36-bcb8-4ecf-85b9-df2de83c9ea8)

### References / Verweise

*

**Comment by jochenklar** [comment]
Hey @chsinn , thanks for reporting, I already found the problem. Whenever you copy an element, the new element gets injected into the old elements "parent". I will fix it asap.
