### ISSUE TITLE
Dynamic Option Sets in RDMO 2.1.1

### ISSUE THREAD

**Issue by MarcoReidelbach** [rdmorganiser/rdmo#893]
### Description / Beschreibung

When using dynamic option sets in RMDO 2.1.1, e.g. through the re3-data plugin, all selectable options in the questionnaire are just 'text'. Is this a bug or do we need to adjust the provider? 

![Screenshot from 2023-12-29 14-49-08](https://github.com/rdmorganiser/rdmo/assets/93648881/3b623fa4-e169-4261-a863-dc75a4758321)

(In `projects/viewsets.py` 'text_and_help': 'text' seems to be added to all option dictionaries generated by the provider. The value from 'text_and_help' (i.e. 'text') is then shown in the interface.) 

### Expected behaviour / Erwartetes Verhalten

Show meaningful options in questionnaire (as is previous versions), e.g. the value from 'text' and not from 'text_and_help' or let the provider define the value in 'text_and_help'?   

### Steps to reproduce / Schritte zum Reproduzieren

Go to the questionnaire and answer a question with dynamic option set.

**Comment by jochenklar** [comment]
Thanks for reporting, we already fixed the issue and will release a new RDMO version ASAP. (https://github.com/rdmorganiser/rdmo/pull/892/commits/38b4e86a6fec69601e1f2db256248248011991b8 :flushed:)
