### ISSUE TITLE
Missing icons on management page

### ISSUE THREAD

**Issue by johlton** [rdmorganiser/rdmo#906]
### Description / Beschreibung

Since the upgrade to version 2 the icons are missing on "Management" page. Console tells me:
```
GET http://rdmo.localhost/static/management/css/fonts/fontawesome-webfont.woff2
[HTTP/1.1 404 Not Found 0ms]
GET http://rdmo.localhost/static/management/css/fonts/fontawesome-webfont.woff
[HTTP/1.1 404 Not Found 0ms]
GET http://rdmo.localhost/static/management/css/fonts/fontawesome-webfont.ttf
[HTTP/1.1 404 Not Found 0ms]
```
It mistakenly tries to load them from `/static/management/css/fonts/`. I cannot rule out webserver configuration completely but nothing funky there:
```
location / {
  proxy_set_header Host $http_host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_pass http://unix:/var/run/gunicorn-rdmo.sock;
}

location /static/ {
  alias /srv/git/rdmo/static_root/;
}
```
`BASE_URL` setting in `local.yml` is commented out for other reasons but reverting this made no difference.

### Expected behaviour / Erwartetes Verhalten

The icons are loading.

### Steps to reproduce / Schritte zum Reproduzieren

1. Login as admin user
2. Click on 'Management'
3. Open js console

### Context / Kontext

Ubuntu 22.04, RDMO 2.1.1, Firefox 121.0.1 (64-Bit)

**Comment by MyPyDavid** [comment]
the 2.1.2 release is for this bug https://github.com/rdmorganiser/rdmo/releases/tag/2.1.2
wanna try upgrade first?

**Comment by johlton** [comment]
Sorry, totally overlooked this. Works of course ;)

**Comment by MyPyDavid** [comment]
nice 😅
