### ISSUE TITLE
`site` should be optional in rdmo.management.rules

### ISSUE THREAD

**Issue by jochenklar** [rdmorganiser/rdmo#914]
At one point we changed

```
{% test_rule 'management.can_view_management' request.user as can_view_management %}
```

to

```
{% test_rule 'management.can_view_management' request.user request.site as can_view_management %}
```

I think it should also work without the site for regular, one site instances. What do you think @MyPyDavid?

**Comment by MyPyDavid** [comment]
yes, think it's fine. We have a custom version of the `rdmo/core/templates/core/base_navigation.html` in most cases anyways.
* https://github.com/rdmorganiser/rdmo/blob/35a576b9c537a8355229dee4b55484cd997da441/rdmo/core/templates/core/base_navigation.html

**Comment by MyPyDavid** [comment]
Is there still any reason for this change request? 
Regular single site instances also have `SITE_ID = 1` anyways
Would it require changes in the rules backend?
please clarify or close it..

**Comment by jochenklar** [comment]
I think it was because if non multi site folks work on the theme they can omit it. But they will copy paste it from the rdmo template anyway I guess.
