### ISSUE TITLE
Export links in Management not working from subdirectory 

### ISSUE THREAD

**Issue by johlton** [rdmorganiser/rdmo#915]
### Description / Beschreibung

The export links aka API URLs in Management GUI are not working if RDMO is running in subdirectory.

### Expected behaviour / Erwartetes Verhalten

I would expect a link with the current subdirectory.
Therefore I would expect an `API_URL` setting in `config/settings/__init__.py`, if not already present somewhere deeper in the code.

### Steps to reproduce / Schritte zum Reproduzieren

1. Configure webserver to serve RDMO from domain subdirectory
2. Set `BASE_URL` in `config/settings/local.py` to subdirectory
3. Go to "Management"
4. Click on a sidebar link within "Export"
5. See a HTTP 404 since the base URL is not included

### Context / Kontext

RDMO 2.1.2

**Comment by jochenklar** [comment]
Hi @johlton , thanks for reporting, the fix will be released in RDMO 2.1.3 (hopefully today).

**Comment by jochenklar** [comment]
Will be part of the next release.
