### ISSUE TITLE
Wrong ordering

### ISSUE THREAD

**Issue by leucoryx** [rdmorganiser/rdmo#944]
![Fragenkatalog_Buttons](https://github.com/rdmorganiser/rdmo/assets/33422021/f458a29e-36db-4f2c-b27f-15ce1bb80b3d)

 You can create a question directly from a page. You have three options:
"Add existing element", "Create new question set" or "Create new question". 

Incorrectly, if you click on "Create new question set", a new question is created and if you click on "Create new question", a new question set is created. The two links are therefore reversed!

(Version 2.1.3)

**Comment by MyPyDavid** [comment]
yes, thanks! the texts of the buttons are swapped: 
https://github.com/rdmorganiser/rdmo/blob/c945d7d9ef5efdccb2d7b41b914ff50ea6f7b49c/rdmo/management/assets/js/components/edit/EditPage.js#L73-L74

**Comment by jochenklar** [comment]
This will be part of the next release.
