### ISSUE TITLE
Cannot remove an external connection

### ISSUE THREAD

**Issue by johlton** [rdmorganiser/rdmo#994]
### Description / Beschreibung

Removing an external connection via `account/social/connections/` fails. By choosing the third party account (in our case ORCID) and hitting "Remove selected account" the message appears: "Your account has no password set up."

![Screenshot 2024-05-15 at 15-06-58 TUB-DMP Testinstanz](https://github.com/rdmorganiser/rdmo/assets/2682391/6e87d10d-c3bd-4f77-a413-7ad144f18bb5)

`local.py`:
````
[...]
SOCIALACCOUNT = True
SOCIALACCOUNT_SIGNUP = True
SOCIALACCOUNT_AUTO_SIGNUP = False
PROFILE_UPDATE = True
PROFILE_DELETE = True

INSTALLED_APPS += [
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.orcid',
]

AUTHENTICATION_BACKENDS.append('allauth.account.auth_backends.AuthenticationBackend')
MIDDLEWARE.append('allauth.account.middleware.AccountMiddleware')
[...]
````

Could be a django-all-auth problem but it's rather an integration thing.

### Expected behaviour / Erwartetes Verhalten

The connection gets deleted.

### Steps to reproduce / Schritte zum Reproduzieren

1. Login via third party, here: ORCID
2. Click on "Account connections"
3. Enable checkbox with a connected account
4. Hit "Remove selected account"

### Context / Kontext

Linux, RDMO 2.1.3

Thanks!

**Comment by jochenklar** [comment]
I have not tried it, but I guess that allauth wants you to set a password first, since otherwise the user cannot login again. I think this is ok, or do you expect something else?

**Comment by johlton** [comment]
Thanks @jochenklar, but if I log-in with a third party account there is neither an option to do that nor a reason to  store password in RDMO. That's the whole point of an external authentication, isn't it ;)

**Comment by MyPyDavid** [comment]
to what kind of account was it connected before? a local account , another social account?

**Comment by johlton** [comment]
Hey, @MyPyDavid , none. I even get the following page after logging on the 3rd party service:
![Screenshot 2024-05-15 at 17-24-54 TUB-DMP Testinstanz](https://github.com/rdmorganiser/rdmo/assets/2682391/0000046c-7f6f-4e5e-9586-4f3863c9ae75)

**Comment by johlton** [comment]
Tried to  reproduce with the GitHub provider: same thing

![Screenshot 2024-05-16 at 08-55-05 TUB-DMP Testinstanz](https://github.com/rdmorganiser/rdmo/assets/2682391/4cfee7d3-ca99-4521-be86-fa103e18ed3d)

**Comment by MyPyDavid** [comment]
> Hey, @MyPyDavid , none. I even get the following page after logging in for the 1st time on the 3rd party service and redirection to RDMO

I think that you get this form because of `SOCIALACCOUNT_AUTO_SIGNUP = False`, see https://docs.allauth.org/en/latest/socialaccount/configuration.html

>  If a conflict arises due to a duplicate email address the signup form will still kick in.  

did this happen?

**Comment by johlton** [comment]
Hey @MyPyDavid , good guess. But unfortunately not the case. The used email address is unique in the system.

**Comment by johlton** [comment]
I also tried to set `SOCIALACCOUNT_AUTO_SIGNUP = True` but after authentication (the form does naturally not appear) it still does not let me delete the connection by myself.

**Comment by MyPyDavid** [comment]
I just tried to reproduce and got the same. 
I login via ORCID> sign up new user >then try to remove the ORCID account connection > get "Your account has no password set up."

But what are you trying to do here? When a user logged in and signed up with ORCID as the only connection, it would not make sense to delete that (thereby locking themselves out of their own account)...??

Maybe the error message is wrong here, but if the user had a local account with a password it would probably work.

You can try to add the Github and then remove the ORCID, that should work. When you want to remove the user account, it goes via Delete Profile..

**Comment by johlton** [comment]
Yeah, thanks, @MyPyDavid , I understand. I assumed it's the same as "Delete Profile" (which logs you out as well), only for external connections. Sorry, my logic.

Signing in via ORCID, then adding the GitHub account and removing the ORCID connection works! The error message is confusing though, but I understand it's on the "django-all-auth" side.

**Comment by jochenklar** [comment]
I think the set password form is disabled in your case. We control that with `ACCOUNT`, which might not be sufficiant. The usual flow would be that users first log in with ORCID then set their own password and then remove the connection. However this case might not happen to often with RDMO. We could adjust the message so that it says "you cannot remove the last connection if no password was set" or so.

**Comment by johlton** [comment]
> We could adjust the message so that it says "you cannot remove the last connection if no password was set" or so.

I would love to see that :) Thanks!
